### PR TITLE
Change Sites tree renderer to use L&F colours

### LINKED ISSUE #3351: the url disappear when i click it
testtest1
testtest2

as the picture i uploaded above,when i click the url , it disappeared.

### PR DESCRIPTION
**Pull request by thc202**
Change SiteMapTreeCellRenderer to use the colours of current L&F for
foreground colour of the text.

Fix #3351 - the url disappear when i click it

### CODE REVIEW

**Comment by thc202** [comment]
I'm assuming that this change fixes the issue (I was not able to test the fix on macOS).

**Comment by davidbernick** [comment]
Does not appear to be fixed in Weekly Release.

screen shot 2017-04-15 at 7 05 28 am

**Comment by thc202** [comment]
Thanks for trying it.

**Comment by thc202** [comment]
@davidbernick would you be OK using a different zaproxy repo (my fork) to build ZAP? I'd like to avoid merging the changes in case it does not fix the issue, like this one :)
(Note that I didn't push the changes yet.)

**Comment by thc202** [comment]
Pull request opened, #3420.

**Pull request merged**
