### PR TITLE
Add LGTM.com badge to README

### PR DESCRIPTION
**Pull request by samlanning**
Hey there,

I see that you've been using LGTM's PR integration, and fixing a load of LGTM issues, e.g: #4927. That's really awesome! zaproxy also has an `A+` rating for the Java Code, so you may like the idea of adding some of the LGTM badges to your README along with all the others you have there :slightly_smiling_face: 

Here's what they look like:

[Language grade: Java](https://lgtm.com/projects/g/zaproxy/zaproxy/context:java)
[Total alerts](https://lgtm.com/projects/g/zaproxy/zaproxy/alerts/)

Let me know if you have any questions about LGTM etc..

cc @psiinon

### CODE REVIEW

**Comment by psiinon** [comment]
Thats our plan, but we want to get the 'alert's badge to green first :)

**Comment by samlanning** [comment]
> Thats our plan, but we want to get the 'alert's badge to green first :)

Aha, that's good to hear!

FTR, the alerts badge there is very primitive in deciding the colour, it is green only when the alerts are 0, not sure if that influences your decision (maybe you want to just add the grade), but you can see the implementation here, and update it if you wish: https://github.com/badges/shields/blob/bedba47d777cb3b27467fa8b020ac4c5a0105fdd/services/lgtm/lgtm-alerts.service.js#L33

**Comment by psiinon** [comment]
OK, thats pretty strict, but I guess its a good target :)
I'm ok with adding them as per this PR then.

**Comment by psiinon** [comment]
@thc202 @kingthorin wdyt?

**Comment by kingthorin** [comment]
I’d say just go with the quality badge.

**Comment by thc202** [comment]
Same here.

**Comment by psiinon** [comment]
I'm good with that.

**Comment by thc202** [comment]
Thanks @samlanning and @kingthorin :)

**Comment by samlanning** [comment]
Awesome thanks!

**Pull request merged**
