### PR TITLE
Fixes #2080

### LINKED ISSUE #2080: Access to HTTPSessions for Site via Script
Hi,

i am currently developing a Proxy Script which needs to work with the sessions of a specific site.
Most methods in the HttpSessionsSite class are already public but these 4 would be required to access them first of all:

```
ExtensionHttpSessions.java
    protected HttpSessionsSite getHttpSessionsSite(String site) 
    protected HttpSessionsSite getHttpSessionsSite(String site, boolean createIfNeeded)

HttpSessionsSite.java
    protected Set<HttpSession> getHttpSessions()    
    protected HttpSession getHttpSession(String name)
```

Best Regards, 
Martin

### PR DESCRIPTION
**Pull request by Harinus**
Set methods to public as requested #2080

### CODE REVIEW

**Comment by psiinon** [comment]
Any particular reason why you added the getNextSessionId() method?

**Comment by Harinus** [comment]
Yes, I am interacting with the sessions as mentioned in Issue 2080 and in addition to use the existing ones i want to create new ones which are not named like "Session XY" but "Custom Text XY". Everything required for it is already there but getting the next available ID was missing.

**Comment by Harinus** [comment]
You may also use the function in this line: https://github.com/zaproxy/zaproxy/blob/394fa83a30e36f31969ff300762f50b1afa85aa0/src/org/zaproxy/zap/extension/httpsessions/HttpSessionsSite.java#L226

**Comment by thc202** [comment]
@Harinus could you give more details on what you want to achieve? Maybe it's possible to do what you want without exposing even more internal (mutable) state, like adding methods to ExtensionHttpSessions (e.g. getHttpSessions(String site), getHttpSession(String site, String sessionName), createHttpSession(String site, String sessionName)...).

**Comment by Harinus** [comment]
@thc202  I am writing a HTTP Sender script which adds Selenium Authentication. Because all existing Authentication Methods are not reliable enough. It is not yet finished but everything works so far.. I will offer the final version once it is done and the required Methods are added or set public.

```
def responseReceived(msg, initiator, helper): 
	#print('responseReceived called for url=' + msg.getRequestHeader().getURI().toString())
		
	if initiator == 2 or initiator == 3 or initiator == 4 or initiator == 6:	
		print msg.getResponseHeader().toString()
		
		logoutIndicators = []
		logoutIndicators.append("STATUS .*401")
		logoutIndicators.append("STATUS .*302 AND HEADER .*Location.*login")
		logoutIndicators.append("STATUS .*200 AND BODY .*Please login")
 
		if  regparser(logoutIndicators, msg):
			print "AUTHENTICATION REQUIRED! Your initiator is: " + str(initiator)
			
			import os
			import org.parosproxy.paros.control.Control
			import org.zaproxy.zap.extension.httpsessions.ExtensionHttpSessions
			import org.zaproxy.zap.extension.httpsessions.HttpSessionsSite
			
			zapsessions = org.parosproxy.paros.control.Control.getSingleton().getExtensionLoader().getExtension(org.zaproxy.zap.extension.httpsessions.ExtensionHttpSessions.NAME)
			sessionSite = zapsessions.getHttpSessionsSite("ipw-test.rsint.net:443", False)
			#Todo: Fetch Site from request

			if sessionSite.getHttpSession("Auth-Selenium") is not None:
				sessionSite.createEmptySession("Re-Auth-Selenium " + str(sessionSite.getNextSessionId()))
			else:
				sessionSite.createEmptySession("Auth-Selenium")
			
			import subprocess as sub
			selenese = sub.Popen("java -jar C:\Users\xyz\Desktop\selenese-runner.jar --strict-exit-code --proxy localhost:8080 --screenshot-on-fail C:\Users\xyz\Desktop\screens --set-speed 1000 --cli-args about:blank C:\Users\xyz\Desktop\ipw-test.html", stdout=sub.PIPE)
			#Todo: Proper location
			output = selenese.communicate()[0]
			returns = selenese.returncode

			if returns != 0:	
				print "AUTHENTICATION FAILURE!"
				print output
			else:
				print "Auth-SUCCESS"
			
		else: 
			pass
			#print "rcv-ignore"

	else:
		pass
		#print "via-proxy " + str(msg.getResponseHeader().getStatusCode())

```

**Comment by thc202** [comment]
OK, would you be available to expose the required functionality through ExtensionHttpSessions class?

**Comment by Harinus** [comment]
@thc202  Could you be a bit more specific? The required getNextSessionId() Method can be moved to ExtensionHttpSessions class but it makes more sense in HttpSessionsSite as it is Site specific.

I don't know if thats what you mean but it might be useful to integrate Selenium Authentication directly into ZAP and not via Script as I did. 

I suggest putting it right next to all the other Authentication Methods: 

test

As (new) Input Fields it would be required to specify the Path to the Selenium Testcase.
And to specify the logged out indicators in the following format: (Which is much more specific and clearer to use than the existing two fields.

```
logoutIndicators.append({'STATUS':'401'})
logoutIndicators.append({'STATUS':'302', 'HEADER':'Location.*login'})
logoutIndicators.append({'STATUS':'200', 'BODY':'Please login'})
```

BUT: Before such huge changes are made it would be enough to find some Testers for the "Scripted-Version" When it runs smooth for everyone someone may integrate it directly.
test2

**Comment by thc202** [comment]
Sure, I was thinking on something like:
```Java
public HttpSession createEmptyHttpSession(String site, String sessionName) {
    HttpSessionsSite httpSessionsSite = getHttpSessionsSite(site, true);
    httpSessionsSite.createEmptySession(sessionName);
    return httpSessionsSite.getHttpSession(sessionName);
}

public HttpSession getHttpSession(String site, String sessionName) {
    HttpSessionsSite httpSessionsSite = getHttpSessionsSite(site, false);
    if (httpSessionsSite != null) {
        return httpSessionsSite.getHttpSession(sessionName);
    }
    return null;
}

public boolean removeHttpSession(String site, String sessionName) {
    HttpSessionsSite httpSessionsSite = getHttpSessionsSite(site, false);
    if (httpSessionsSite == null) {
        return false;
    }
    HttpSession session = httpSessionsSite.getHttpSession(sessionName);
    if (session == null) {
        return false;
    }
    httpSessionsSite.removeHttpSession(session);
    return true;
}

public boolean setActiveHttpSession(String site, String sessionName) {
    HttpSessionsSite httpSessionsSite = getHttpSessionsSite(site, false);
    if (httpSessionsSite == null) {
        return false;
    }
    HttpSession session = httpSessionsSite.getHttpSession(sessionName);
    if (session == null) {
        return false;
    }
    httpSessionsSite.setActiveSession(session);
    return true;
}

public boolean unsetActiveHttpSession(String site) {
    HttpSessionsSite httpSessionsSite = getHttpSessionsSite(site, false);
    if (httpSessionsSite == null) {
        return false;
    }
    httpSessionsSite.unsetActiveSession();
    return true;
}
```

Yes, the counter does not need to be exposed through the extension.
(Note though that `lastGeneratedSessionID` is shared by all Sites, not that it matters much).

Agreed, the script could be added to community-scripts. [1]

[1] https://github.com/zaproxy/community-scripts

**Comment by Harinus** [comment]
ok, now i got your idea. But i dont see any advantage of masquerading those methods in the Extension class. However thats a questing of Code Design and you can implement it the way you like it more.

As far as i see every Site has its own lastGeneratedSessionID which makes sense.

I will add the script when it reaches a final state.
For now it can be accessed here: https://github.com/Harinus/ZAP-Selenium-Auth

**Comment by kingthorin** [comment]
Could you fix-up or squash this into a single "atomic commit"?
https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#what-we-zap-team-expect-from-you

**Comment by kingthorin** [comment]
Could you fix-up or squash this into a single "atomic commit"?
https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#what-we-zap-team-expect-from-you

**Comment by Harinus** [comment]
This problem is older than one year.. i will have a look at it within the next few days..

**Comment by kingthorin** [comment]
@Harinus I know :cry: trying to address the backlog.

Thanks for your support.

I'm not sure if there were other changes still needed, so please feel free to set this PR (branch) to allow modification by maintainers:
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Pull request closed without merging**
