### PR TITLE
Fix JavaDoc issues

### PR DESCRIPTION
**Pull request by sigee**

### CODE REVIEW

**Comment by thc202** [comment]
I'm not sure there's any advantage fixing JavaDoc problems in deprecated classes.

**Comment by sigee** [comment]
> I'm not sure there's any advantage fixing JavaDoc problems in deprecated classes.

You may be right, but from a clean code perspective, If you need code, you should keep them clean. If you don't need the code. remove it. If it is deprecated but needed, keeping it clean is still a good practice in my opinion.

**Comment by thc202** [comment]
In an ideal world, yes, you can have that perspective no matter what.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you! (While I still think this is not needed, it's less JavaDoc warnings so…)

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
