### PR TITLE
Add button to install all add-ons from marketplace

### PR DESCRIPTION
**Pull request by thc202**
Add a button, shown in dev mode only, to install all add-ons available
in the marketplace, to not require selecting them one by one.

### CODE REVIEW

**Comment by psiinon** [comment]
Out of interest whats the use case for this?
I know we have a command line option for this, but that was intended more for testing than anything else.
Has anyone asked for this?

**Comment by thc202** [comment]
Personal use mainly, I usually want to install all of them when trying changes that might affect the add-ons (and this changes makes it a lot faster).

**Comment by psiinon** [comment]
Maybe only enable this in dev mode then?
I cant see it being very useful for most ZAP users - the UI is complicated enough without them having absolutely everything installed :/

**Comment by thc202** [comment]
Yeah, change done.

**Pull request merged**
