### PR TITLE
Added swagger file with some operations

### PR DESCRIPTION
**Pull request by omerlh**
I've created a basic swagger file with 3 operations I needed for Glue. 
What left?
- [ ] Added swagger linter on CI (For example, [this](https://www.npmjs.com/package/swagger-cli) is a good option
- [ ] Publish the swagger somewhere
- [ ] Acceptance tests for the API (maybe using [this](https://apigee.com/about/blog/api-technology/swagger-test-templates-test-your-apis))
- [ ] Generate ruby client

#2033

### CODE REVIEW

**Comment by thc202** [comment]
What's the main purpose? Generate clients? Document the API?

**Comment by omerlh** [comment]
My motivation is a Ruby client, the code on Glue use Curl which kinda works as I find while writing tests for it. It will also helps with documentation, of course.

**Comment by psiinon** [comment]
All of the other API clients use code generation.
I'd recommend either generating the Ruby client in the same way or generating the swagger file.
The current generators are all in https://github.com/zaproxy/zaproxy/tree/develop/src/org/zaproxy/zap/extension/api
Please dont do it by hand :)

**Comment by omerlh** [comment]
I am familiar with both options. Generating the swagger automatically is not a simple task, same as creating ruby client generator. I was thinking to create it manually as a step forward automatic generation of the swagger.

**Comment by psiinon** [comment]
How about discussing this on the dev list first?
I'm not sure I like the idea of PRs just raised for the purposes of discussion. I'm concerned that they will make it harder for us to review PRs.
I also wouldnt want us to merge a PR that could require us to manually maintain a swagger spec going forwards.
Other thoughts appreciated...

**Comment by kingthorin** [comment]
I agree.
https://groups.google.com/forum/#!forum/zaproxy-develop

**Comment by psiinon** [comment]
Have chatted about this with @thc202 as well, and it looks like we're all in agreement.
PRs should be, in the view of their authors, ready to merge.
Happy for you to create a tracker issue and/or develop this in your own fork, but I dont think we should have incomplete tracker PRs.

**Pull request closed without merging**
