### PR TITLE
Update webswing

### PR DESCRIPTION
**Pull request by psiinon**
Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
FYI I've added the new WEBSWING_URL secret.

**Review by kingthorin — APPROVED** [review]

**Comment by psiinon** [comment]
Updated to extract the WebSwing version. Have updated the secret accordingly.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by thc202** [comment]
The changelog could mention the update though.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you again :)

**Pull request merged**
