### PR TITLE
Baseline - use AF by default if supported

### PR DESCRIPTION
**Pull request by psiinon**
Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
Worth update the changelog.

**Comment by psiinon** [comment]
Doh, of course!

**Comment by psiinon** [comment]
Done :)

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
