### PR TITLE
Allow java max mem to be overridden on the cmdline

### PR DESCRIPTION
**Pull request by psiinon**

### CODE REVIEW

**Comment by kingthorin** [comment]
Is this meant to address https://github.com/zaproxy/zaproxy/issues/382? If so should it include a similar mod for zap.bat?

On it's own this change looks OK to me.

**Comment by thc202** [comment]
Works fine here.

Though this addresses #382, I'd close #382 as duplicate of #1795 (which applies to zap.sh and zap.bat).

**Comment by psiinon** [comment]
Is it possible to do something similar in zap.bat? Not with my limited knowledge ;)
Not sure how many people actually use the bat file, I'd expect most people to use the exe. And the bat file doesnt have any equivalent code for determining the memory available.
This change helps with the docker images, as you can then set the memory without having to create a new file on the docker images.

**Comment by kingthorin** [comment]
Ok, I'm good with that reasoning.

**Pull request merged**
