### PR TITLE
Run tests with JUnit 5

### PR DESCRIPTION
**Pull request by thc202**
Add dependency on JUnit 5 and remove JUnit 4.
Use Mockito library for JUnit 5.

Change tests to:
 - Use new annotations/imports;
 - Inline temporary directories when just needed in few tests;
 - Assert exceptions with `assertThrows`;
 - Explicitly assert that no exception is thrown (in tests that had no
  assertion and where no exception is expected);
 - Make more mocks lenient where needed.

### CODE REVIEW

**Comment by thc202** [comment]
Excluded JUnit 4 introduced by WireMock, updated imports to use Hamcrest's `assertThat`.

**Comment by psiinon** [comment]
Now conflicting

**Comment by thc202** [comment]
Yeah, changed to WIP, need to review latest tests added/changed as well.

**Comment by thc202** [comment]
Conflicts resolved and updated tests added in the meantime.

**Pull request merged**
