### PR TITLE
Fix FPs in isSuccess and isPage200

### PR DESCRIPTION
**Pull request by psiinon**
Fix for https://groups.google.com/g/zaproxy-users/c/QCfFo7Nh1sI/m/KABs-yyRAAAJ and https://github.com/zaproxy/zaproxy/issues/8234

The latter was fixed via https://github.com/zaproxy/zap-extensions/pull/5232 but I did not submit the core change at that time 😦  This is that change 😁

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by psiinon** [comment]
@kingthorin want to check this again?

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Shall we just do away with the analyser if we aren't going to trust/fix it?

**Comment by psiinon** [comment]
Possibly yes .. but maybe we should investigate it further, and maybe fix it if we can?

**Comment by thc202** [comment]
It's still good at telling (custom) 404s (and is still used for that).

**Pull request merged**
