### PR TITLE
fix: Disable FlatLaf native decorations on windows

### PR DESCRIPTION
**Pull request by kingthorin**
Native Decorations were causing various issues for me:
- ZAP wouldn't start maximized.
- Split pane dividers would drift noticeably between starts of ZAP.
- The close button would sometimes be inaccessible.

See: https://github.com/JFormDesigner/FlatLaf/pull/267 for further details.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
It still worth checking if there's an issue in our code or in FlatLaf (or something in between).

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Well, that, if the features provided are wanted.

**Review by psiinon — APPROVED** [review]

**Comment by DevCharly** [comment]
> Native Decorations were causing various issues for me:
>  * ZAP wouldn't start maximized.
>  * Split pane dividers would drift noticeably between starts of ZAP.
>  * The close button would sometimes be inaccessible.

I've fixed an issue in FlatLaf related to starting maximized (for FlatLaf 1.2; coming soon).
It works now in ZAP with enabled native decorations.

Also the inaccessible close button should be fixed.
(if it still occurs in ZAP, please let me know)

Regarding the drifting split pane dividers:
- when starting ZAP non-maximized, they are stable
- when starting ZAP maximized, they drift

But not only in FlatLaf.
They drift also in other Lafs (e.g. Windows Laf).
Looks like an issue in ZAP with saving/restoring divider locations in **maximized** state.

If you want try out the latest FlatLaf build:
https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by kingthorin** [comment]
Thanks @DevCharly!

**Comment by kingthorin** [comment]
Looks like 1.2 is now available: https://github.com/JFormDesigner/FlatLaf/releases I'll doing some testing and put together a PR.

**Comment by kingthorin** [comment]
I have verified that with 1.2 ZAP will start maximized and that the close button seems properly accessible (clickable).

Sadly the drifting dividers does still happen. I haven't investigated where/if this is saved/restored.

To start with I'll just do a PR with the dependency update, but leaving the native decorations off until I can discuss the divider issue with someone.

**Pull request merged**
