### PR TITLE
(refactor) use of the multi-catch construct... fixing pull-request #3600.

### PR DESCRIPTION
**Pull request by rbonifacio**
(refactor) to use multi-catch in some try-cactch-statements. add ZAP comments + fix indentation problems, according to the comments of a previous pull request https://github.com/zaproxy/zaproxy/pull/3600

<sub>Edited: by @kingthorin 20170531 to add details and ref original PR.</sub>

### CODE REVIEW

**Comment by kingthorin** [comment]
Thanks!

**Comment by thc202** [comment]
Thank you!

**Comment by thc202** [comment]
@rbonifacio how would you like to be credited?
https://github.com/zaproxy/zap-core-help/wiki/HelpCredits

**Comment by rbonifacio** [comment]
@thc202, perhaps as a ZAP Extended Team. I hope that I could contribute with other useful refactoring efforts. Thanks!

**Comment by kingthorin** [comment]
@rbonifacio it would be in that section. He meant specifically do you want your full name used? Username? Both.... have a look at what others have done and let us know.

**Comment by rbonifacio** [comment]
@kingthorin It might be Rodrigo Bonifácio. Thanks for the clarification.

**Pull request merged**
