### PR TITLE
Add SARIF report command line argument to baseline scan

### PR DESCRIPTION
**Pull request by oseki-guy**
Signed-off-by: Mister Oseki <113904192+oseki-guy@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
IMO we shouldn't be adding more features to the packaged scans, Automation Framework is the path forward.

**Comment by kingthorin** [comment]
?

**Comment by thc202** [comment]
It seems the pull request now has unrelated changes.

**Comment by kingthorin** [comment]
This really seems like something that should have been discussed before hand or tackled as an individual/org customization.

I don’t recall us indicating that we’re giving up on the webswing implementation or moving away from dockerhub. Plus the earlier point about packaged scans vs automation framework.

**Comment by oseki-guy** [comment]
I did experiment on that fork of zaproxy but I did not mean to open this PR. Sorry for the noise :bow:

**Comment by kingthorin** [comment]
@oseki-guy thanks for letting us know. If there is something here that makes sense for the project feel free to start a discussion on the [Developer Group](https://groups.google.com/g/zaproxy-develop)

**Pull request closed without merging**
