### PR TITLE
chore: Remove use of "and/or" in user facing strings

### PR DESCRIPTION
**Pull request by kingthorin**
Going along with my old writing rant: http://andore.ddns.net

Remaining occurrences are in the license header `(?<!it )and\/or` or other code comments.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
While I tackled this I also noticed that the API uses "scanners" in a bunch of places it should probably use "scan rules", both in endpoint/param description(s) and in actual endpoints. Think that's work fixing? (I guess the endpoints would have to be deprecated/replaced or maybe again just do the user facing strings?)

**Comment by thc202** [comment]
The referenced link does not work.

**Comment by kingthorin** [comment]
Tweaked :) Apparently it's a lame http link :)

**Comment by ricekot** [comment]
The commit message could also be updated.

**Comment by thc202** [comment]
I'm fine with these changes (IMO languages/English are not boolean arithmetic though), as long as we are consistent throughout. The dev guidelines should be updated.

Don't think worth changing the endpoints.

**Review by thc202 — APPROVED** [review]

**Comment by kingthorin** [comment]
I agree it's not boolean logic. But, in like 98% of cases the "or" is really fine, and the "and/or" just looks rushed or something...

**Comment by kingthorin** [comment]
I will tweak the commit message like @ricekot suggested. Just need to finish my work day and do a few family things.

**Comment by kingthorin** [comment]
Tweaked commit message.

**Comment by psiinon** [comment]
I wonder how many of these I added :P 
In any casse I think its good to be consistant and I'm ok with us not using this term :)

**Review by psiinon — APPROVED** [review]

**Pull request merged**
