### PR TITLE
Allow to instantiate AbstractFrame

### PR DESCRIPTION
**Pull request by thc202**
Do not require to extend the class to use it, it's not needed.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
Seems fine to me. Will that cause any problems for extensions?

**Comment by thc202** [comment]
It's a compatible change, it might cause problems if something is using reflection and checking if it's abstract but unlikely.

**Review by ricekot — APPROVED** [review]
Thanks!

**Comment by thc202** [comment]
Actually, this does cause problems with JavaScript scripts that are extending it... ironically this change is to allow them to be used with GraalJS engine.

**Comment by kingthorin** [comment]
So revert this or modify the scripts? Or ______ ?

**Comment by thc202** [comment]
Modify the scripts, which was already the plan (though I was not expecting that to break in the meantime).

**Pull request merged**
