### PR TITLE
Move (non-dist) doc files to top level directory

### PR DESCRIPTION
**Pull request by thc202**
Move non-distribution doc files to top level directory, those are not
bundled with ZAP.
Update links to one of the files in scripts bundled in Docker images.

### CODE REVIEW

**Comment by thc202** [comment]
That's a good question, I think the former, the SQLi plugin still set the properties but that's it, `Kb` is not much used. Maybe something to deprecate and remove?

**Comment by kingthorin** [comment]
I don't think the whole thing should be removed. I was just wondering about that doc piece. I see the value in having it, and ZAP could definitely leverage it more.

image

**Comment by thc202** [comment]
OK. I was not counting that one, `AbstractAppFilePlugin` will be removed once #3563 lands.

**Comment by kingthorin** [comment]
Oh ok, I wasn't assuming any specific timing for that one so figured it may as well be doc'd.

Plus I had idea of tech detection or tracking (kinda like the SQLi one) in the back of my head.

**Pull request merged**
