### PR TITLE
Small Title Caps Fix-View Toolbar

### PR DESCRIPTION
**Pull request by Sebitosh**
Related to issue #2000

Hi! I was looking to do a first contribution and stumbled across the title caps issue. I looked a bit around the obvious places in the GUI and noticed one inconsistency in the view toolbar.

Signed-off-by: Sébastien Amelinckx <sebastien111@hotmail.be>

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
Good catch. Thanks

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by thc202** [comment]
@Sebitosh how would you like to be credited (e.g. name, handle)?
https://www.zaproxy.org/docs/desktop/credits/#zap-extended-team

**Comment by Sebitosh** [comment]
Thanks to you too! And sure I would love to be credited,  if I find the time I'll try to look for other issues I can help with as well.

**Comment by kingthorin** [comment]
Still need to know that name etc to use for the credit :wink:

**Comment by Sebitosh** [comment]
Right ! Sorry I missed that. You can put:
Sébastien Amelinckx (@Sebitosh)

With a link to my github profile in the tag

**Pull request merged**
