### PR TITLE
Docker: Stable/live to debian, remove zapcli, update webswing

### PR DESCRIPTION
**Pull request by psiinon**
Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by psiinon** [comment]
WIP while I double check the bare image..

**Comment by psiinon** [comment]
I've changed bare to use `openjdk:11-jre` - it went down from 1.33GB to 875MB
Should we look at using that for the other images as well??

**Comment by psiinon** [comment]
Arg https://hub.docker.com/_/openjdk - Deprecation notice ☹️  Will have to choose another one...

**Comment by psiinon** [comment]
I've changed bare to use `eclipse-temurin:11-jre-alpine` - thats maintained and brings us down to 714MB
Note that it uses `apk` so if anyone builds on top of it they will probably have to change things.
If we're all ok with this I'll send a msg to the user group and it will get a mention in the release notes...

**Comment by kingthorin** [comment]
The bare image seems to be using both apt-get and apk currently

**Comment by psiinon** [comment]
Thats because the builder is using a different image :)
Can look at changing that as well if people think its important...

**Comment by kingthorin** [comment]
No, I just didn’t catch the detail. Thanks.

**Review by thc202 — APPROVED** [review]

**Pull request merged**
