### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Thor07**
Apostrophe added

### CODE REVIEW

**Comment by Thor07** [comment]
@thc202 Please review and merge. Thanks!

**Comment by kingthorin** [comment]
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Comment by thc202** [comment]
Set DCO to pass since it's a typo fix.

**Comment by thc202** [comment]
Thank you!

**Comment by thc202** [comment]
Just noticed this was merged to master...

**Comment by kingthorin** [comment]
I'll re-create on `develop`

**Pull request merged**
