### PR TITLE
Update startup script for newer Java version

### PR DESCRIPTION
**Pull request by thc202**
Remove unnecessary Java version check and require newer Java version.

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Comment by kingthorin** [comment]
Does the bat require similar changes?

**Comment by kingthorin** [comment]
Or the installer? (I forget if there’s config there that needs tweaking)

**Comment by thc202** [comment]
The `bat` does not check the Java version. The installers will have more changes, will do all at once.

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Thanks

**Pull request merged**
