### PR TITLE
Update Id occurrences to full caps (ID)

### PR DESCRIPTION
**Pull request by kingthorin**
Related to zaproxy/zaproxy#2000 and https://github.com/zaproxy/zap-core-help/pull/480#discussion_r1083236916

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
This should be changed consistently, there are occurrences in the API.

**Comment by kingthorin** [comment]
Thanks, I didn't even think to look there. Will tackle that too.

**Comment by kingthorin** [comment]
That should be all of them.

**Review by ricekot — APPROVED** [review]
Thanks!

**Review by psiinon — APPROVED** [review]
I had to do a search to check which was right 😉 
https://ux.stackexchange.com/questions/50983/spelling-id-vs-id

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
