### PR TITLE
added healthchek to docker images

### LINKED ISSUE #3649: Add docker health check
Dockerfile allow you to declare [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) command. It would be great to add this command to the docker image, and report Zap as healthy when it complete loading. This could be useful when using Zap in CI environment (using `docker-compose`), and waiting to Zap to complete loading before starting the tests. The only problem is how we detect that Zap complete loading - I think the API is responsive before Zap complete loading.

### PR DESCRIPTION
**Pull request by omerlh**
close #3649

### CODE REVIEW

**Comment by thc202** [comment]
Thanks!

**Comment by thc202** [comment]
In the pull request description the issue should be 3649 ;)

**Comment by omerlh** [comment]
Fixed :)

**Comment by thc202** [comment]
@omerlh how would you like to be credited?
https://github.com/zaproxy/zap-core-help/wiki/HelpCredits

**Comment by thc202** [comment]
OK, which name/handle should we use?

**Comment by omerlh** [comment]
Omer Levi Hevroni

**Pull request merged**
