### PR TITLE
Update test_zap.config

### PR DESCRIPTION
**Pull request by tkisason**
typo fixes

### CODE REVIEW

**Comment by kingthorin** [comment]
Looks good

**Comment by thc202** [comment]
Looks good to me (although last line could be left unchanged?), thanks.

**Comment by kingthorin** [comment]
@tkisason any chance you could revert the trailing line feed change?

**Comment by tkisason** [comment]
No problem, is it ok now?

**Comment by thc202** [comment]
The newline is still there, might be being added automatically by the editor?
Could you fix up the commits?

**Comment by tkisason** [comment]
Don't know why, i'm looking at https://github.com/tkisason/zaproxy/blob/ffa852e1ab16eea5242ca151850137dbe50ab429/python/scripts/generic-pytest/test_zap.config , which is the last commit and it doesn't have the trailing newline...

**Comment by thc202** [comment]
I checked out the branch and the file still has the newline, looking at commit tkisason/zaproxy@ffa852e1ab16eea5242ca151850137dbe50ab429 (and previous one) it does not seem to have done any change to the newline.

**Comment by kingthorin** [comment]
Latest commit:

> No changes to show.
> This commit has no content.

**Comment by kingthorin** [comment]
@tkisason could you fix-up or squash this into a single "atomic" commit?

https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#what-we-zap-team-expect-from-you

**Comment by thc202** [comment]
Rebased and merged. Thank you for the contribution!

**Pull request closed without merging**
