### PR TITLE
Register and reserve types of context data

### PR DESCRIPTION
**Pull request by thc202**
Register types already in use, by alert filters and custom pages.
Reserve a range for the AJAX spider.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
I don’t disagree but what are these used for?

**Comment by thc202** [comment]
Load and persist context data, e.g.: https://github.com/zaproxy/zaproxy/blob/f8852857ea2a2c2b238ef3866fb1310541e4f59c/zap/src/main/java/org/zaproxy/zap/extension/custompages/ExtensionCustomPages.java#L202-L228

**Comment by kingthorin** [comment]
Has it been defaulting to zero or something?

I don’t recall seeing warnings or errors ☹️ Sorry I missed it during the implementation.

**Comment by thc202** [comment]
They are already using those values, they have their own constants/types though. The `RecordContext` is not needed/used directly so I didn't replace the other constant, but they still should be added there for documentation purposes.

**Comment by kingthorin** [comment]
Okay, thanks!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
