### PR TITLE
Add SSTI scanners ID

### PR DESCRIPTION
**Pull request by DiogoMRSilva**
Added the scanner Ids for SSTI scanner and SSTI blind scanner.

### CODE REVIEW

**Comment by thc202** [comment]
Could you amend the commit with signed-off? https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s

**Comment by DiogoMRSilva** [comment]
@thc202 done

**Comment by thc202** [comment]
Thank you!

**Comment by DiogoMRSilva** [comment]
It's my pleasure.

**Pull request merged**
