### PR TITLE
chore: Update FLatLaf to 1.2

### PR DESCRIPTION
**Pull request by kingthorin**
Update L&F dependency.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
The legal notice file should be updated. It's missing a space after L&F.

**Comment by kingthorin** [comment]
Will tweak both later this evening

**Comment by kingthorin** [comment]
Done & done

**Review by ricekot — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
