### PR TITLE
AbstractAppVariantPlugin for the usecases where ScanRule needs to manipulate multiple namevalue pairs.

### PR DESCRIPTION
**Pull request by preetkaran20**
This is the new PR with the earlier changes as discussed in https://github.com/zaproxy/zaproxy/pull/6371

### CODE REVIEW

**Comment by preetkaran20** [comment]
Hi @thc202  @kingthorin 
please review.

**Comment by preetkaran20** [comment]
Hi @thc202  @kingthorin 
please review.

**Comment by thc202** [comment]
Why a new PR? The discussions were still ongoing (e.g. the need for a new class; the API to set multiple parameters), not that we can't continue in this one but the context is lost.

**Comment by preetkaran20** [comment]
> Why a new PR? The discussions were still ongoing (e.g. the need for a new class; the API to set multiple parameters), not that we can't continue in this one but the context is lost.

I have reopened the earlier one too. Lets discuss on any one. Actually i sometimes face issues with handling multiple branches. Will try to handle from next time.

**Pull request closed without merging**
