### PR TITLE
Added changes to issue "Unable to enable/disable Forced User mode without main tool bar #2744"

### PR DESCRIPTION
**Pull request by shivanXI**
thc202 Please have a review on the PR i have opened and comment for changes needed.

### CODE REVIEW

**Comment by kingthorin** [comment]
Well for starters resolving the conflict would be good :smiley:

**Comment by kingthorin** [comment]
Why does this require changes to more files than githhb.com can display and diff?

**Comment by kingthorin** [comment]
..,think you probably merged changes instead of rebasing?

**Comment by shivanXI** [comment]
Yes, unfortunately i merged old files instead of fetching and rebasing updates due to misconception ,apologies for that; making it right asap

**Comment by kingthorin** [comment]
Haha no problem at all. I had a rough while getting used to git too :smiley:

**Comment by kingthorin** [comment]
@shivanXI are further updates for this PR coming? There seems to be a number of changes included that should not have been.

**Comment by kingthorin** [comment]
@shivanXI are further updates for this PR coming? There seems to be a number of changes included that should not have been.

**Comment by shivanXI** [comment]
Apologies for late reply and I am currently not able to work on this PR and
so no.update is available in current time.

**Comment by kingthorin** [comment]
@shivanXI could you set this PR to allow modification by maintainers?
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by thc202** [comment]
Conflicts resolved and branch rebased.

The changes for the issue are incomplete though. I'm fine finishing that if no one has the time.

**Comment by kingthorin** [comment]
Seems to be failing build now. I'm fine with you doing the changes or talking through it and tackling it...

**Comment by thc202** [comment]
Branch rebased and changes finished.

**Comment by thc202** [comment]
Conflict resolved.

**Comment by thc202** [comment]
@psiinon looks good?

**Comment by psiinon** [comment]
yep :)

**Comment by thc202** [comment]
Thank you!

**Comment by thc202** [comment]
@shivanXI how would you like to be credited?
https://github.com/zaproxy/zap-core-help/wiki/HelpCredits

**Pull request merged**
