### PR TITLE
Validate i18n time stamp patterns

### PR DESCRIPTION
**Pull request by thc202**
Add test to check that the internationalised time stamp patterns are
valid.

---
The build will fail, some of the patterns are not correct and others have the char `'` incorrectly escaped. Plan to fix that in Crowdin.

### CODE REVIEW

**Comment by thc202** [comment]
It seems the right place for that, not all patterns will be the same for all locales (e.g. `DD-MM` vs `MM-DD`). I think we could hardcode the ISO 8601 pattern as that's the same for all of them?

**Comment by kingthorin** [comment]
Ok I'll put that on my todo list :zap:

**Comment by thc202** [comment]
OK, thanks.

**Comment by thc202** [comment]
The incorrect patterns are now fixed in Crowdin.

**Comment by psiinon** [comment]
Unit tests still failing.

**Comment by thc202** [comment]
Now passing (needed a rebase to pick latest Crowdin changes).

**Pull request merged**
