### PR TITLE
Build ZAP with Gradle

### PR DESCRIPTION
**Pull request by thc202**
Apply changes to build ZAP with Gradle, for easier review it's split into several commits.

The zaproxy repo needs to be (re)imported into IDEs as a Gradle project.
(When running ZAP from the IDE the working directory needs to be set to `zaproxy/zap/src/main/dist` to pick the add-ons copied to the `plugin` dir.)

The following table shows the corresponding Gradle tasks for the (old) Ant targets:

| Ant Targets              | Gradle Tasks                           |
|:-------------------------|:---------------------------------------|
| `package-daily`          | `:zap:distDaily`                       |
| `package-lite`           | `:zap:distCore`                        |
| `package-linux`          | `:zap:distLinux` and `:zap:distDebian` |
| `package-macosx`         | `:zap:distMac`                         |
| `generate-apis`          | `:zap:generateAllApiEndpoints`         |
| `generate-javadocs`      | `:zap:javadocs`                        |
| `generate-language-file` | `:zap:copyLangPack`                    |
| `test`                   | `:zap:test`                            |

The installers can be built with the task `:zap:installers`.

To run ZAP from the source use the task `:zap:run`.
To publish ZAP to Maven Central use the task `:zap:publish`.

### CODE REVIEW

**Comment by thc202** [comment]
I was not able to test the Windows 64bits installer nor macOS package (don't have the OSes at hand).

**Comment by kingthorin** [comment]
Tried to build the installers on Win7 (64) (Java 8u211).
```
> Task :zap:createExe
Security framework of XStream not initialized, XStream is probably vulnerable.

> Task :zap:prepareWin32InstallerData
> Task :zap:prepareWin64InstallerData
> Task :zap:installers FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':zap:installers'.
> installation directory "C:\fred\ZAP_DEV\zap-workspace2\zaproxy\zap\null" does not exist
```

Will try building on a Kali VM...

**Comment by kingthorin** [comment]
Essentially got the same result on Kali:
```
> installation directory "/root/git/zaproxy/zap/null" does not exist
```

**Comment by kingthorin** [comment]
Both of those were from within Eclipse. Trying gradlew (CLI) on Kali now.

**Comment by thc202** [comment]
I guess you didn't define the install4j home? https://github.com/zaproxy/zaproxy/pull/5369/files#diff-396d0b75211f5646b2fa730fbdf80a40R66

That needs to provide a better error message...

**Comment by kingthorin** [comment]
Yup totally missed that. Will try it again tomorrow.

**Comment by thc202** [comment]
Added the error message for when the install4j home dir is not set and rebased to pick the latest test.

**Comment by psiinon** [comment]
@kingthorin the plan now is to get this and related PRs merged, generate the weekly and then test the installers.
So if you're happy with the non installer related changes then can you approve it?

**Pull request merged**
