### PR TITLE
Integration tests - add user/next/pwd auth cases

### PR DESCRIPTION
**Pull request by psiinon**
Also added a summary which makes it easier to see what passed with all of the browser output 😁 
Example (end of) output:
```
Summary:
 Plan: auth-json-bearer-cookie.yaml	PASS
 Plan: auth-json-bearer.yaml	PASS
 Plan: auth-non-std-json-bearer.yaml	PASS
 Plan: auth-password-added-json.yaml	PASS
 Plan: auth-password-hidden-json.yaml	PASS
 Plan: auth-password-new-json.yaml	PASS
 Plan: auth-simple-json.yaml	PASS
 Plan: jigsaw-basic-user.yaml	PASS
 Plan: petstore-openapi.yaml	PASS
 Plan: testfire-form-user.yaml	PASS

End result: 0
```

### CODE REVIEW

**Comment by kingthorin** [comment]
Could I suggest either?
`End Result: 10`
or
`End Errors: 0` (or "Failures" if that's more accurate.)

**Review by kingthorin — COMMENTED** [review]
LGTM just that one minor comment.

**Comment by psiinon** [comment]
> Could I suggest either? `End Result: 10` or `End Errors: 0` (or "Failures" if that's more accurate.)

You can, but its not what this is saying 😁 
Thats actually the result code returned - "0" means success. On failure it will return "1", not the number of tests that failed.
So I dont think it should be changed...

**Comment by psiinon** [comment]
I could change it to `Returned Result` ?

**Comment by psiinon** [comment]
Have changed to `Exit Code` 😁

**Comment by kingthorin** [comment]
Thanks :grinning:

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
