### PR TITLE
Improved Python API library

### PR DESCRIPTION
**Pull request by cr0hn**
Add: support for Python 3 and some improvements. Now the API runs in Python 2 and 3
Add: high performance json library to improve coding/encoding
Add: request library to simplify handling of proxies
Add: Transparent transparent in-memory cache for queries
Fix: setup.py - Now the dist generation, dependecies and upload to pypi is more simple.
Imp: Improved source code to be more PEP-8 compilant
Imp: Changes in code to be more "pythonic". Some parts of code smells Java :)

### CODE REVIEW

**Comment by psiinon** [comment]
Ha! Would have been good to mention you were looking at this - I've also been changing the API to support Python 2 and 3! And its been taking me too long as I'm no python expert ;)
Unfortunately you've manually changed a load of files marked "This file was automatically generated." - you need to change the generator file: https://github.com/zaproxy/zaproxy/blob/develop/src/org/zaproxy/zap/extension/api/PythonAPIGenerator.java - thats the one that creates the generated files.
But you changes sound really good :)
You feel up to changing the generator?

**Comment by cr0hn** [comment]
I'm starting to use the Python library for a personal project, and probably I'll include more improvements (like coroutines in request). 

Ups, I doesn't knew you're improving the library :(

I can try to take a look to the generator, but I'm not a Java developer. I'll see the code and I say something.

**Comment by psiinon** [comment]
See #2308 
I _am_ a java dev, so I can help with that :) 
Changing __init__.py is fine.
Let me know if you have problems understanding / changing the generator, I wront that so between us we should be able to get it all working correctly:)

**Comment by thc202** [comment]
@psiinon a good opportunity to move the Python API to other repo?

**Comment by cr0hn** [comment]
Seen the issue :)

The patch I sent, made the code runs in Python 2 and 3. And, coming soon with new features of Python 3.4 and greater.

Taking a look to the code, I understand that the main function of it is the generation of end points, right?

Maybe we can adopt an hybrid approach, generating with the generator the end points, and using the rest .py as static. Doing so, I can send more updated without change the generator code.

If you like the idea, the changes in the endpoint generation are:

**Import Six**
Importing six library in each file:

`import six`

**Iteritems**
`return next(....).itervalues())`
to
`return next(six.itervalues(...))`

Ensuring the compatibility with Python 2 & 3

**Remove parenthesis**
` return (self.zap._request_other(...))`
to
` return self.zap._request_other(...)`

The parenthesis here are redundant.

The rest of modifications are to improve PEP-8, but it's not modify the behavior of code, so it could be as the generator generates.

**Comment by psiinon** [comment]
@cr0hn exactly - the API is defined via Java classes, so we can use code generation to create clients in java, python etc etc. Ok, so we could have used Swagger or something like that, but the API _was_ defined a while ago ;)
The more code we can move into common static classes the better imo - so your suggested approach sounds good to me :)

**Comment by psiinon** [comment]
@cr0hn - is there a std format for python projects? I like @thc202 's suggestion of moving the python API to a new repo now as it will make everything cleaner and easier to manage.

**Comment by cr0hn** [comment]
If we move the code to the new project I also think It could be more clean. I suppose the Zap API is stable and It will not change often. In this case this approach has more sense for me also.

@psiinon In Python the std defined in [PEP-8](https://www.python.org/dev/peps/pep-0008/)

**Comment by psiinon** [comment]
https://github.com/zaproxy/zap-api-python :)
Although I cant actually see the recommendations on directory structure in that link :/
You can submit a PR for the static code whenever its ready - we'll generate the generated code once the generator has been correctly updated (which again, I can help with)

**Comment by cr0hn** [comment]
Ah, ok ok, I don't understood. There are not a STD for structure. The most common are some similar to:

http://docs.python-guide.org/en/latest/writing/structure/

If you want, I can structure the project and send a new update I don't mind. I'll send a PR with the static code.

**Comment by psiinon** [comment]
That would be great :)

**Comment by cr0hn** [comment]
Done :)

**Comment by kingthorin** [comment]
Conflicts need resolution.

**Comment by kingthorin** [comment]
@cr0hn's contributions now in https://github.com/zaproxy/zap-api-python/pulls/cr0hn

**Pull request closed without merging**
