### PR TITLE
Add Java 21 to CI

### PR DESCRIPTION
**Pull request by thc202**
Build with Java 21 which is a LTS version.
Disable the lint `this-escape` to pass the compilation.
Address other warns/deprecations.

### CODE REVIEW

**Comment by thc202** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by thc202** [comment]
Yes, tests were not yet updated.

**Comment by kingthorin** [comment]
Do we/you :wink: need to be opening issues for any of the "deprecation" or "removal" suppressions?

**Comment by thc202** [comment]
Not at this point.

**Review by psiinon — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
