### PR TITLE
Use renderer's label in Sites tree

### LINKED ISSUE #3351: the url disappear when i click it
testtest1
testtest2

as the picture i uploaded above,when i click the url , it disappeared.

### PR DESCRIPTION
**Pull request by thc202**
Change SiteMapTreeCellRenderer to use/add the renderer's label, it
already has and paints the expected colours for fore and background.

Fix #3351 - the url disappear when i click it

### CODE REVIEW

**Comment by thc202** [comment]
Round two (first in #3376), again I was not able to test this change in macOS.

@davidbernick would you be able to test this change?

**Comment by davidbernick** [comment]
Trying now

**Comment by thc202** [comment]
Thanks! It's also included in the weekly release in case it's faster/easier.

**Comment by davidbernick** [comment]
Confirm weekly build 4/18/2017 works!

**Comment by thc202** [comment]
Great, thanks for trying it and letting us know :)

**Pull request merged**
