### PR TITLE
Use non absolute URI base HTML element

### LINKED ISSUE #2939: Use non absolute URI base HTML element in spider
Steps to reproduce the bug.

1) Setup a page with the following content (say at http://host/Zap)

```
<html>
<head>
    <base href="/Zap/" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="/Zap/Content/site.css" rel="stylesheet"/>
    <script src="/Zap/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
<h2>Main Navigation</h2>
<ul>
    <li><a href="/Zap/">Home</a></li>
    <li><a href="/Zap/Testlink">Testlink</a></li>
</ul>
    <script src="/Zap/Scripts/jquery-1.8.2.js"></script>
</body>
</html>
```

2) Setup a trivial page at http://host/Zap/Testlink

3) Use ZAP to spider http://host/Zap

Expected Result:

- ZAP Spider finds  http://host/Zap/Testlink

Actual Result:

- ZAP Spider does not find http://host/Zap/Testlink
- Chrome and IE happily follow the link.
- Removing the line `<base href="/Zap/" />` and running the spider again results in ZAP spider finding http://host/Zap/Testlink

ZAP Version: 2.5.0

### PR DESCRIPTION
**Pull request by thc202**
Change SpiderHtmlParser and SpiderHtmlFormParser to properly handle non
absolute URI base HTML element.
Update tests to reflect the change in the behaviour.
Change form HTML base tests to reuse the same file (have HTML base and
form action as variables).

Fix #2939 - Use non absolute URI base HTML element in spider

### CODE REVIEW

**Comment by kingthorin** [comment]
Looks good to me

**Comment by psiinon** [comment]
Looks good to merge once conflicts have been resolved.

**Comment by thc202** [comment]
Done, also changed the form HTML base tests to reuse the same file.

**Comment by richgmorg** [comment]
That was quick thanks!

**Pull request merged**
