### PR TITLE
Remove GC setting in zapdb.script

### PR DESCRIPTION
**Pull request by bjhulst**
No-op setting previously used to forces garbage collection each time a set number of result set row or cache row objects are created. This setting has no effect in version 2.5.0 or later, (source: http://hsqldb.org/doc/2.0/guide/dbproperties-chapt.html  table 14.70)
This release of zaproxy already uses version 2.5.2.
https://github.com/zaproxy/zaproxy/blob/8ac4b10d3d9d816957985694c2b7cf127d1364d3/zap/zap.gradle.kts

### CODE REVIEW

**Comment by thc202** [comment]
The commit needs to be signed off.

**Comment by kingthorin** [comment]
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Comment by bjhulst** [comment]
Signed-off-by: bjhulst

**Review by bjhulst — COMMENTED** [review]
Signed-off-by: bjhulst

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
