### PR TITLE
Add Request and Response Data to XML Report

### PR DESCRIPTION
**Pull request by andykais**
HttpMessage data is under the `<requestdata>` and `<responsedata>` tag

### CODE REVIEW

**Comment by psiinon** [comment]
Unfortunately this will mean that the request and response data will always be added to all reports.
I'd expect most people _not_ to want this, and even if they did this wouldnt be a good way to do it as it would take up a lot of memory.
We already know ZAP runs out of memory with large numbers of issues even without including this data :/ #1277

**Comment by AndrewKaiser** [comment]
Maybe this is a special case then, though I do believe there are a number of people who may appreciate this feature. What if I were to make it an option in the GUI, in the save dialog maybe?

**Comment by psiinon** [comment]
I can definitely see the benefit of this.
However I believe Sam Hakim is already working on this: https://groups.google.com/d/msg/zaproxy-develop/Yxiv0VrCnTg/pIQD9808ZxIJ 
You could always contact him directly to see where he's up to and if you can help him.

**Comment by AndrewKaiser** [comment]
Alright I'm sure Sam is working on a more sophisticated solution but in case you are interested, I pushed a change that makes adding html data an option in the save dialogue

**Comment by thc202** [comment]
@andykais can this PR be closed with release of "Code Dx" add-on?

**Comment by andykais** [comment]
Yes, that will be fine. We got what we were looking for with the plugin.
Thank you for your quick responses

**Comment by kingthorin** [comment]
Closing per requester feedback.

**Pull request closed without merging**
