### PR TITLE
Issue 3879 - Auto Set Active Imported Certificate

### PR DESCRIPTION
**Pull request by kingthorin**
Automatically activate the first client cert imported.

Fixes zaproxy/zaproxy#3879

### CODE REVIEW

**Comment by kingthorin** [comment]
Wow you were fast on that. I switch tabs and came back and it was labeled 👍

**Comment by thc202** [comment]
Should I push here if I get the PKCS#11 part working (or add diff to issue)?

**Comment by kingthorin** [comment]
I'm fine with you updating this PR. Whichever your prefer. If the PKCS#11 part is burdensome we can always tackle it separate/later.

**Comment by thc202** [comment]
As you mentioned in the issue, it was the same code changes. I moved the code to existing method (which was already being called by both implementations). I also changed the logic to check if there's just one cert instead of just one keystore, as for the latter it would automatically active a cert even if there was more than one (from my understanding of the comments in the issue that was not intended?).

Feel free to fixup, drop, or change the commit as you see fit.

**Comment by kingthorin** [comment]
Looks good to me. Thanks! I'll test it a bit more tomorrow to see the multiple key handling. Maybe I didn't complete adding the second key, or canceled out of the dialog or something...

**Comment by kingthorin** [comment]
Tested this a bit this morning, the PKCS#12 stuff seems to be working as expected. Good with me squashing it, and I guess I'll ask psiinon to review it?

**Comment by thc202** [comment]
Sounds good.

**Comment by kingthorin** [comment]
@psiinon since both @thc202 and I worked on this could you review and merge?

**Comment by psiinon** [comment]
of course :)

**Pull request merged**
