### PR TITLE
Update HarLib

### LINKED ISSUE #5393: Update HarLib library
Update HarLib library to version 1.1.3 (needs to be published to Maven Central first).

### PR DESCRIPTION
**Pull request by thc202**
Update to latest version, 1.1.3.
Update the version of HarLib and its dependency (Jackson Core) in
`LEGALNOTICE`.

Fix #5393.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
And jackson-core?

**Comment by thc202** [comment]
Yeah, that's a dependency of HarLib.

**Comment by kingthorin** [comment]
Mainly wanted to make sure it was intentional, probably best to update the commit message but I'm good with whatever.

**Comment by thc202** [comment]
Tweaked.

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]

**Pull request merged**
