### PR TITLE
Change auth header env vars to use ScriptVars

### PR DESCRIPTION
**Pull request by psiinon**
Allow the auth header env vars to be read and updated by scripts and code.

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Will rework to use ScriptVars based on feedback..

**Comment by psiinon** [comment]
Changed  to use ScripVars under the covers :)
The tests may still fail - they pass locally but for some reason the last tests got different header counts back in CI.
Can fix the tests if it keeps happening ...

**Comment by psiinon** [comment]
That should fix some of them .. expecting other test to still fail..

**Comment by psiinon** [comment]
Doh! I created a new unit test in the wrong package, and it was the old unit test (with the same name) in the right package that was failing 🤣

**Comment by psiinon** [comment]
Test passed 😁 No longer WIP...

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
