### PR TITLE
Find Next/Find Previous

### PR DESCRIPTION
**Pull request by jsoref**
#5744

### CODE REVIEW

**Comment by jsoref** [comment]
Note: I'm naively assuming that "Next" and "Previous" are related to "Find" and not "Search" (and thus that they're in the wrong section).

If they're really "Next search result", then, um... I don't know what the labels should be, but "Next" and "Previous" are wrong.

**Comment by thc202** [comment]
They are part of the search functionality.

**Comment by kingthorin** [comment]
I could merge some variation of this into: https://github.com/zaproxy/zaproxy/pull/5747 if there’s any need/benefit.

**Comment by jsoref** [comment]
ok, so, this isn't the right text. That PR/task is the right direction. `Edit`>`Search`>`Next result` / `Edit`>`Search`>`Previous result` might be better

**Comment by thc202** [comment]
Closing, superseded by #5747.

**Pull request closed without merging**
