### PR TITLE
Add "retire" and "encoder" addons to weekly

### PR DESCRIPTION
**Pull request by kingthorin**
Update weekly-add-ons.json to include recent additions "retire" and "encoder".

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
Is the shortcut going to be removed in other PR?

**Comment by thc202** [comment]
Needs a Spotless.

**Comment by kingthorin** [comment]
Done

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
