### PR TITLE
Report the host:port ZAP is listening on in daemon mode, or exit if it cant

### LINKED ISSUE #1920: Report the host:port ZAP is listening on in daemon mode, or exit if it cant
Following the instructions at https://github.com/zaproxy/zaproxy/wiki/Docker#zap-headless and have the Docker portion installed, but running the following command just stalls "Creating new root CA" (on OS X 10.10.5):

```sh
$ docker run -u zap -p 8080:8080 -i owasp/zap2docker-stable zap.sh -daemon -port 8080

Found Java version 1.7.0_79
Available memory:  996 MB
Setting jvm heap size: -Xmx256m
364 [main] INFO org.zaproxy.zap.DaemonBootstrap  - OWASP ZAP 2.4.2 started.
814 [main] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache open start
826 [main] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache open end
1381 [main] INFO org.parosproxy.paros.network.SSLConnector  - Reading supported SSL/TLS protocols...
1382 [main] INFO org.parosproxy.paros.network.SSLConnector  - Using a SSLEngine...
1721 [main] INFO org.parosproxy.paros.network.SSLConnector  - Done reading supported SSL/TLS protocols: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2]
1741 [main] INFO org.parosproxy.paros.extension.option.OptionsParamCertificate  - Unsafe SSL renegotiation disabled.

...

5771 [Thread-4] INFO org.zaproxy.zap.extension.dynssl.ExtensionDynSSL  - Creating new root CA
```

It's been stuck on that step for ~10m, so I'm guessing it's stuck and it doesn't take that long to create a cert. I've also tried running the command a few times, to make sure it wasn't a 1-time thing.

### PR DESCRIPTION
**Pull request by psiinon**
Fixes #1920 Report the host:port ZAP is listening on in daemon mode, or exit if it cant

### CODE REVIEW

**Comment by kingthorin** [comment]
I just added this type of comment to another issue in the tracker but it's probably also applicable here.

If there user has bound to other than loop local do we want to warn/remind them that exposes ZAP to other network users? (Consider 0.0.0.0 binding, or specifically binding to a non loop local address 1918 or externally routeable)

**Comment by psiinon** [comment]
@kingthorin via a message to stdout? As its not the default, they will have to have chosen to change the configuration..

**Comment by kingthorin** [comment]
Ya. I'm just thinking for instances where someone uses ZAP, doesn't touch it for weeks/months :cry:, then goes back to use it again. We don't need to prevent it, but warning/reminding might be a good move...

**Comment by psiinon** [comment]
I suspect that in daemon mode a log warning will be ignored by everyone. And in UI mode I'm wary of too many popups :/ Maybe we should warn people when they first set the addr via the UI and provide an option to warn them when they restart ZAP?? Might need more thought, so I dont think it should be part of this PR...

**Comment by kingthorin** [comment]
Agreed on all counts

**Pull request merged**
