### PR TITLE
Add "_csrf_token" accepted CSRF token names list

### PR DESCRIPTION
**Pull request by gsmethells**
Add "_csrf_token" to the list of acceptable CSRF token names when scanning for "Absence of Anti-CSRF Tokens".

### CODE REVIEW

**Comment by kingthorin** [comment]
What framework is this related to?

**Comment by gsmethells** [comment]
thc202 on #zaproxy IRC approved adding it for our medical imaging Flask app (https://joints.medstrat.com). It's not in an official framework of Flask.

**Comment by gsmethells** [comment]
I support the Oxford comma as well!

**Comment by gsmethells** [comment]
https://flask-wtf.readthedocs.io/en/0.15.x/csrf/

**Comment by kingthorin** [comment]
Thanks, was just looking for more context 😀

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
