### PR TITLE
Adding FileUpload Scan Rule

### PR DESCRIPTION
**Pull request by preetkaran20**

### CODE REVIEW

**Comment by preetkaran20** [comment]
File Upload Addon: https://github.com/SasanLabs/owasp-zap-fileupload-addon/pull/1

**Comment by thc202** [comment]
Corrected the base branch, it has conflicts now.

**Comment by preetkaran20** [comment]
> Corrected the base branch, it has conflicts now.

thanks @thc202. Will correct it.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by preetkaran20** [comment]
@thc202  thanks. Please also review: https://github.com/SasanLabs/owasp-zap-fileupload-addon/pull/1

thanks,
Karan

**Review by psiinon — APPROVED** [review]

**Pull request merged**
