### PR TITLE
Refactor SessionStructure and Session

### PR DESCRIPTION
**Pull request by psiinon**
This _was_ going to be some Site Tree fixes, but the code was split between SiteTructure and Session, so I'm refactoring it.
This PR should _not_ introduce any functional changes - those will be applied on top of this if/when its merged.

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
If this is ok would be good to get in the weekly :)

**Review by kingthorin — APPROVED** [review]

**Comment by psiinon** [comment]
Updated as requested :)

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thanks!

**Comment by thc202** [comment]
@kingthorin do you want to take another look?

**Review by kingthorin — APPROVED** [review]
Thanks

**Pull request merged**
