### PR TITLE
Register IDs for Community Scripts active scan rules

### PR DESCRIPTION
**Pull request by amankumarchagti**

### CODE REVIEW

**Comment by kingthorin** [comment]
Re: The DCO check we can set it to pass if you can just confirm that you agree with https://www.eclipse.org/legal/DCO.php

**Comment by psiinon** [comment]
FYI I'm guiding @amankumarchagti on this - next task will be to use these in the scan rules :D

**Comment by amankumarchagti** [comment]
I agree to DCO

**Comment by kingthorin** [comment]
Setting DCO pass.
image

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Pull request merged**
