### PR TITLE
Issue 2016: Handle proxy conflict

### PR DESCRIPTION
**Pull request by kingthorin**
- ProxyServer.java - Add functionality to pick a random port and prompt the user to use it (or try one they want).
- Proxy.java - Save the proxy port if it had to be selected during startup.
- ProxyPortRetryPanel - Added to display a custom yes/no dialog and a portSpinner.
- Messages.properties - Added keys/values to support these changes.
- MainFooterPanel.java - Add left footer to display the primary proxy details.
- MainFrame > Used to hook options update functionality.
- View > Used to update the new footer in postInit.

Fixes zaproxy/zaproxy#2016

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Example:
I had apache configured to listen on 3 ports:
```
Listen localhost:8080
Listen localhost:8081
Listen localhost:8082
```

image

**Comment by thc202** [comment]
The prompt is also being shown for additional proxies (at start up and after closing the Options dialogue, the later for main proxy too).

**Comment by kingthorin** [comment]
I was about to get the startup additional proxies thing to happen, but I'm not able to recreate the other two. Zap won't let me change to a used port or add on an used port.

**Comment by thc202** [comment]
Launch ZAP twice with the same configs, it should reproduce both cases.

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
