### PR TITLE
Added script loading parameter for baseline

### PR DESCRIPTION
**Pull request by Zilborg**
I used it for authentication and csrf scripts.
Issue: #6930

### CODE REVIEW

**Comment by psiinon** [comment]
This can already be acheived via the script options. The options support all scriptin g engines, unlike this PR which just supports Zest and Nashorn.
As per https://github.com/zaproxy/zaproxy/issues/6930#issuecomment-970083672 I dont think we should be extending the packaged scripts as they have proved difficult to support and maintain.

**Comment by psiinon** [comment]
Thanks for the PR btw, but we are looking to migrate the packaged scan scripts to use the Authentication Framework not extend them.

**Comment by psiinon** [comment]
To do the same thing via the existing options should be something like: `-z "-config dirs=/zap/wrk/scripts"`

**Comment by Zilborg** [comment]
> To do the same thing via the existing options should be something like: `-z "-config dirs=/zap/wrk/scripts"`

Oh, I see.
Thanks for your time!

**Pull request closed without merging**
