### PR TITLE
Use try-with-resources for a better code

### PR DESCRIPTION
**Pull request by matteobaccan**
Hi

I have introduced the use of try-with-resources in some classes

all the best
matteo baccan

### CODE REVIEW

**Comment by thc202** [comment]
https://github.com/zaproxy/zaproxy/pull/6552#issuecomment-822582488

**Comment by thc202** [comment]
@matteobaccan can you confirm that you agree with DCO?

**Comment by matteobaccan** [comment]
> 
> 
> @matteobaccan can you confirm that you agree with DCO?

Yes, I agree the DCO

**Comment by kingthorin** [comment]
> > @matteobaccan can you confirm that you agree with DCO?
> 
> Yes, I agree the DCO

Set DCO check to pass, per user agreement.

**Comment by thc202** [comment]
Merged the try-with-resource statements to reduce unnecessary nesting.
Added the ZAP comment to Paros class.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]
Thank you both

**Pull request merged**
