### PR TITLE
Address lint issues

### PR DESCRIPTION
**Pull request by thc202**
- Remove redundant type arguments 
 - Remove empty statements 
 - Add missing override annotations
 - Remove redundant interface declaration
 - Reduce accessibility in tests

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
Great, thanks

**Comment by psiinon** [comment]
LGTM :)

**Comment by thc202** [comment]
Pushed more changes, should be ready to review.

**Review by kingthorin — APPROVED** [review]
Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
