### PR TITLE
Fixed German translation for ascan.options.level.*.label

### PR DESCRIPTION
**Pull request by KevinLapagna**
German meaning of .low.label and .high.label was inverted.
It is now a direct translation of the English wording.

### CODE REVIEW

**Comment by psiinon** [comment]
Thanks for fixing this @KevinLapagna but we actually manage all of the translations in Crowdin: https://crowdin.net/project/owasp-zap
We have automated jobs which pull the Crowdin translations and submit them to us as PRs, so if the values are just changed in github then they will get overwritten.
So please sign up to Crowdin (its free:) and change them there - our tools will do the rest :)

**Comment by thc202** [comment]
@KevinLapagna thanks for doing the changes in Crowdin. How would you like to be credited? [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpCredits#zap-localization

**Comment by KevinLapagna** [comment]
@thc202 As 'Kevin Lapagna' would be just fine. If at all - it's just a very small fix.

**Comment by thc202** [comment]
Done in zaproxy/zap-core-help@c044984b63a35b8a11acd6d41f31fc1b11308995. Thank you!

**Pull request closed without merging**
