### PR TITLE
Show HTTP messages in the Spider tab

### PR DESCRIPTION
**Pull request by thc202**
Add a button to tool bar of Spider tab to allow to see the HTTP messages
sent while spidering. When the button is selected the panel shows two
tabs, one for the URLs and the other for the HTTP messages, otherwise it
just shows the table with the URLs found, as before.

### CODE REVIEW

**Comment by psiinon** [comment]
Looks good

**Comment by kingthorin** [comment]
@thc202 if you'd rebase this I'd be glad to merge it.

**Comment by thc202** [comment]
Conflict resolved and updated to show the highest alert and tags in the messages tab.

**Comment by kingthorin** [comment]
Thanks

**Comment by kingthorin** [comment]
Looks like this actually fixes the outstanding item in https://github.com/zaproxy/zaproxy/issues/353 which I had marked as wontfix.

**Comment by thc202** [comment]
Yeah, it does fix that. Should it be updated to reflect that? (i.e. remove the label and set it for 2.5.0)

**Comment by kingthorin** [comment]
I just added a comment to zaproxy/#353, removed the wontfix label, and added the Milestone.

**Comment by thc202** [comment]
Thanks for updating the issue :)

**Pull request merged**
