### PR TITLE
Registered 'Cookie set without SameSite attribute'

### PR DESCRIPTION
**Pull request by psiinon**

### CODE REVIEW

**Comment by thc202** [comment]
Looks good to me.

**Comment by psiinon** [comment]
@thc202 has just spotted an error, so dont merge yet. I'm also hopefully going to be able to add some unit tests as well

**Comment by psiinon** [comment]
ugh, wrong PR - this ones hopefully fine ;)

**Comment by kingthorin** [comment]
Looks goodLeave a comment

**Pull request merged**
