### PR TITLE
Update scanners.md for JWT Scanner addon

### PR DESCRIPTION
**Pull request by preetkaran20**

### CODE REVIEW

**Comment by kingthorin** [comment]
https://github.com/SasanLabs/owasp-zap-jwt-addon/blob/32281fdc71d7864f758ec78fccf2e3ea010e1597/src/main/java/org/zaproxy/zap/extension/jwt/JWTActiveScanner.java#L51 Will need to be updated to align with this.

**Comment by preetkaran20** [comment]
> https://github.com/SasanLabs/owasp-zap-jwt-addon/blob/32281fdc71d7864f758ec78fccf2e3ea010e1597/src/main/java/org/zaproxy/zap/extension/jwt/JWTActiveScanner.java#L51 Will need to be updated to align with this.

@kingthorin yes, i didn't updated because i was not sure if this change it correct or not. Will do the change. One question how does a addon appear on the zap market place ?

**Comment by kingthorin** [comment]
When it’s ready to release you’ll just fill out this issue template: https://github.com/zaproxy/zaproxy/issues/new?labels=marketplace&template=Third_party_addon.md

**Comment by thc202** [comment]
How about the other scan rule? The client one being its own rule, which might as well be a passive scan rule as it does not send any request?

**Pull request merged**
