### PR TITLE
Allow underscore character in context structural parameter name

### LINKED ISSUE #3069: Context structural parameter only accepts alphanumeric charts
Hi, we try to use ZAP for scan of Spring Webflow based application deployed on Liferay. The URL parameter that determines the flow id and position contains underscores, and it cant be added as Structural Parameter in ContextStructurePanel.
Is there any reason to validate parameters on alphanum chars and do not allow e.g. underscores?

### PR DESCRIPTION
**Pull request by martinkalina**
Fixes #3069

### CODE REVIEW

**Comment by thc202** [comment]
Could you change the pull request description to fix the issue? [1]

[1] https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by thc202** [comment]
@martinkalina thanks! How would you like to be credited?
https://github.com/zaproxy/zap-core-help/wiki/HelpCredits

**Comment by martinkalina** [comment]
@thc202 you're welcome! my real name is Martin Kalina if you mean to add me to list of contributors. Anyway I have to contribute more than one character in the future ;-)

**Comment by psiinon** [comment]
We all have to start somewhere :)
I started by copying the 'Resend' right click option from the History tab into the Sites tab (or the other way round, cant really remember which). No really new functionality, just a very small usability improvement. But one thing led to another ...

**Comment by martinkalina** [comment]
well, in the next months I have to adopt ZAP in our project, and I will have to extend it . So fixing issues seems a good way to get some knowledge of code in this project.

**Comment by psiinon** [comment]
Thats good to hear :) Keep in touch via the [ZAP Dev Group](https://groups.google.com/group/zaproxy-develop) - you never know someone might already be working on some of the changes you need.

**Pull request merged**
