### PR TITLE
Use selected font in Request/Response panels

### LINKED ISSUE #3490: Poor font rendering on linux
Would it be possible to do something with font rendering in owasp zap on linux?

Please compare the request/response font rendering of owasp zap with burp:

screenshot from 2017-05-05 18-02-25

screenshot from 2017-05-05 18-00-44

The screenshots were made on Kali xfce (but on pure Debian with gnome it looks similarly bad).

I'm using `_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp'` in `/etc/environment`. 

```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

I've also changed the interface font in zap (to Input Mono 16) - it looks slightly better with it.

It's hard to read the source/request/response code in zap, with better font rendering burp is much more pleasant in this regard. Shame, as zap is a great tool.

Thanks for your work.

### PR DESCRIPTION
**Pull request by thc202**
Change HttpPanelSyntaxHighlightTextArea to use the font selected in the
options or use default font of the component (e.g. monospaced).
Change FontUtils to allow to check if a custom font was set.

Fix #3490 - Poor font rendering on linux

### CODE REVIEW

**Comment by thc202** [comment]
This should address #3490, but waiting for comments on the preferred behaviour (https://github.com/zaproxy/zaproxy/issues/3490#issuecomment-325817971).

**Comment by ksdev-pl** [comment]
I've tried your change and with a custom font it looks much better!

screenshot from 2017-09-01 14-59-24
(This is on Debian Stretch)

Thank you very much, you're the best!

**Comment by kingthorin** [comment]
@ksdev thanks for letting us know.

**Comment by psiinon** [comment]
Sudden thought - does this work ok with the font scaling?

**Comment by ksdev-pl** [comment]
In Gnome there is no difference with a different font scaling (when a custom font is selected):
screenshot from 2017-09-04 10-50-06

**Comment by thc202** [comment]
I think @psiinon is referring to https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsView#font-size

With these changes it still uses that option.

**Comment by thc202** [comment]
Updated to use the default font of the component (instead of system default), to keep the same behaviour as before when no font is selected.

**Pull request merged**
