### PR TITLE
dependency updates

### PR DESCRIPTION
**Pull request by kingthorin**
Update dependencies declared in various build files, and legal notice.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Reverted hsql library update as it fails on Java 8.

**Review by ricekot — APPROVED** [review]
LGTM, thanks!

**Comment by thc202** [comment]
HSQLDB is already at the latest version: https://github.com/zaproxy/zaproxy/pull/6542#issue-614738693

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
