### PR TITLE
Add initiator constant for Forced Browse requests

### PR DESCRIPTION
**Pull request by thc202**
Add a constant to HttpSender class for requests sent by the Forced
Browse add-on.

Related to #3060 - Send Forced Browse requests through ZAP

### CODE REVIEW

**Comment by thc202** [comment]
Same comment, Brute Force add-on was not yet changed to use that (worst in this case, as it will require a lot more changes...).

**Comment by kingthorin** [comment]
Ok

**Comment by psiinon** [comment]
Looks good but now has conflicts

**Comment by thc202** [comment]
Conflict resolved.

**Pull request merged**
