### PR TITLE
Wire in site mod changes

### PR DESCRIPTION
**Pull request by psiinon**
Not sure how this got left out - it was there in my original PR otherwise this would never have worked :/
Will look at implementing suitable tests but really want to get this in for the weekly...

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by psiinon** [comment]
Just added a unit test for this.

**Review by kingthorin — APPROVED** [review]
Still looks good, tks

**Review by kingthorin — APPROVED** [review]
Still look good, thanks

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
