### PR TITLE
updating API-Minimal policy in Docker

### PR DESCRIPTION
**Pull request by PyaeHlianMoe**
reformat the policy file and removed the deprecated rules from the policy.

### CODE REVIEW

**Comment by psiinon** [comment]
@Pyae-Hlian-Moe why did you delete this PR?
It was on my list to review ASAP..

**Comment by PyaeHlianMoe** [comment]
Hi @psiinon I have created a new PR https://github.com/zaproxy/zaproxy/pull/8257. This one is closed due to the wrong account I have used.

**Comment by thc202** [comment]
You don't need to close the PR for that, you can amend the commit and force push.

**Comment by PyaeHlianMoe** [comment]
Thanks for the guidance. Apology that I didn't do it. Should I amend this PR's commit and close the new one I just opened? Or should I just leave as it is?

**Comment by thc202** [comment]
No worries, just saying in case you need to adjust future PRs. You can leave as is.

**Pull request closed without merging**
