### PR TITLE
Set X-ZAP-Scan-ID header in the right HttpMessage instance.

### PR DESCRIPTION
**Pull request by sbaranov-parasoft**
Fixes zaproxy#6689

### CODE REVIEW

**Comment by kingthorin** [comment]
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

---

Also do you want to tweak the details you committed with?
https://github.com/zaproxy/zaproxy/commit/bf00da1ed65ebab1e43f6765502fbdee837f2d74.patch

**Comment by thc202** [comment]
This should have a test, might need a ZAP comment.

**Comment by thc202** [comment]
Added the test and ZAP comment.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]
Thank you both!

**Pull request merged**
