### PR TITLE
#6098: Allowing to pass request headers from a spider parser to the spider task

### PR DESCRIPTION
**Pull request by vladidx**
- Extended SpiderParserListener interface with additional methods
- New methods in SpiderParser including listener notifications
- Extended mechanism to track visited GET/POST requests with headers as part of the SpiderController
- SpiderTask receives request headers and adds them to the created HttpMessage request header
- Adapted SpiderParserTestUtils to reflect header changes

Related to #6098

### CODE REVIEW

**Comment by vladidx** [comment]
Tooks some attempts but now the checks are green.

An open question from my side would if/how to test the enhancement as existing spiders do not make use of the new feature (yet?).

**Comment by vladidx** [comment]
@thc202 / @psiinon: Any suggestion how to proceed further with this PR?

**Comment by thc202** [comment]
> An open question from my side would if/how to test the enhancement as existing spiders do not make use of the new feature (yet?).

The `SpiderParser` can be tested in isolation, just need to spy and verify that it calls the correct methods of the listener.

> Any suggestion how to proceed further with this PR?

I'd suggest extracting a class for the resource found (containing the source URI, URI, depth, method, body, headers...), it would not require keeping adding more constructors/methods each time we allow to provide more data about the resource and should simplify the handling of GET/POST in the controller. We should have done this before... I'm happy to do that if you don't want to refactor though.

**Comment by vladidx** [comment]
I can try to implement an additional unit test for adding request headers and also refactor the handling of resources detected by spider implementations.

Regarding the refactoring: Is it necessary to retain binary compatibility in the `SpiderParserListener` interface (implemented by SpiderController and TestSpiderController)? If not we could have a single interface method handled by the controller, e.g.
`public resourceFound(SpiderResourceFound resource)`

**Comment by thc202** [comment]
It would be better if we kept binary compatibility, but I guess we can break it in this case. I don't see a reason why the add-ons would be implementing/using the listener directly, and a quick search in GitHub didn't show up anything.

**Pull request closed without merging**
