### PR TITLE
Exclude browser/OS updates by default

### PR DESCRIPTION
**Pull request by psiinon**
These are typically just noise. Things like Google analytics havnt been included as they might leak "interesting" data...

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Should this include an update method in the Constant class?

**Comment by psiinon** [comment]
Ricardo asked that on IRC as well 😉 
I'm in 2 minds myself - I think it could be a pain to do and the medium term plan is now to move these to the network add-on and implement them as passthroughs (post 2.12)...

**Comment by kingthorin** [comment]
Okay I’m that case let’s not overthink it. We can note it in the release notes, and any release blog that’s done.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
