### PR TITLE
Update coverity_scan from develop

### PR DESCRIPTION
**Pull request by zapbot**
Autogenerated PR from zapbot

### CODE REVIEW

**Comment by psiinon** [comment]
This pull request **fixes 61 alerts** when merging fccf9a36cfb42421638bf48b577e6b4a099fe50e into 3da7c9c1e2a3f7033575f4a51ad464c9066d1e36 - [view on LGTM.com](https://lgtm.com/projects/g/zaproxy/zaproxy/rev/pr-e1a651abf2d9e1cf0535b905ed5a2dd1fe6b4d07)

**fixed alerts:**

* 36 for Potential database resource leak
* 25 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kingthorin** [comment]
The Java 11 install failed?

**Comment by thc202** [comment]
Caused by problems with `jdk.java.net`, https://github.com/travis-ci/travis-ci/issues/9987.

**Comment by thc202** [comment]
All builds passing.

**Pull request merged**
