### PR TITLE
Support packaged authenticated scans

### PR DESCRIPTION
**Pull request by psiinon**
Also tweaked the error handling - no popint in dumping the zap.log if its a user error and made sure the scripts return 3 on any exceptions.

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Fixed the test failure.

**Review by kingthorin — APPROVED** [review]

**Comment by psiinon** [comment]
Note that as it stands this will break existing scan hooks, which is not ideal.
Discussing various options in irc...

**Comment by psiinon** [comment]
Fixed the problem with existing hook files, and tweaked the code to find hook files in the cwd - I had to debug the scripts to work out why mine wasnt being found ;)

**Comment by psiinon** [comment]
And added more tests

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
