### PR TITLE
Update FlatLaf

### PR DESCRIPTION
**Pull request by thc202**
Update to latest version, 1.6.3.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by DevCharly** [comment]
Maybe better wait for 1.6.3.
There is a regression in 1.6.2 that may display text in non-editable combo boxes in bold. (see FlatLaf issue 423)

**Comment by kingthorin** [comment]
Thanks for the warning

**Comment by DevCharly** [comment]
FlatLaf 1.6.3 is released 😃

**Comment by thc202** [comment]
Thank you! Pull request updated.

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]

**Comment by kingthorin** [comment]
Thanks for the heads-up @DevCharly

**Pull request merged**
