### PR TITLE
Pin non-GitHub actions with full sha in workflows

### PR DESCRIPTION
**Pull request by kingthorin**

### CODE REVIEW

**Comment by psiinon** [comment]
Logo
**Checkmarx One – Scan Summary & Details** – [b79dad88\-ac65\-4f48\-b2f5\-eeb29bb3cbcd](https://eu.ast.checkmarx.net/projects/641c4d0f-0dae-4786-973b-ead9338157fd/scans?id=b79dad88-ac65-4f48-b2f5-eeb29bb3cbcd&branch=kingthorin%2Fpin-actions-sha)
### Fixed Issues
Severity|Issue|Source File / Package
---|---|---
LOW|Unpinned Actions Full Length Commit SHA|/release\-weekly\-docker\.yml: [27](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-weekly-docker.yml#L27)
LOW|Unpinned Actions Full Length Commit SHA|/release\-weekly\-docker\.yml: [36](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-weekly-docker.yml#L36)
LOW|Unpinned Actions Full Length Commit SHA|/release\-main\-docker\.yml: [72](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-main-docker.yml#L72)
LOW|Unpinned Actions Full Length Commit SHA|/release\-main\-docker\.yml: [27](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-main-docker.yml#L27)
LOW|Unpinned Actions Full Length Commit SHA|/release\-weekly\-docker\.yml: [30](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-weekly-docker.yml#L30)
LOW|Unpinned Actions Full Length Commit SHA|/release\-live\-docker\.yml: [22](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-live-docker.yml#L22)
LOW|Unpinned Actions Full Length Commit SHA|/release\-live\-docker\.yml: [34](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-live-docker.yml#L34)
LOW|Unpinned Actions Full Length Commit SHA|/release\-weekly\-docker\.yml: [43](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-weekly-docker.yml#L43)
LOW|Unpinned Actions Full Length Commit SHA|/run\-integration\-tests\.yml: [19](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/run-integration-tests.yml#L19)
LOW|Unpinned Actions Full Length Commit SHA|/lock\.yml: [15](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/lock.yml#L15)
LOW|Unpinned Actions Full Length Commit SHA|/release\-live\-docker\.yml: [25](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-live-docker.yml#L25)
LOW|Unpinned Actions Full Length Commit SHA|/release\-live\-docker\.yml: [28](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-live-docker.yml#L28)
LOW|Unpinned Actions Full Length Commit SHA|/ci\.yml: [27](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/ci.yml#L27)
LOW|Unpinned Actions Full Length Commit SHA|/run\-integration\-tests\.yml: [16](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/run-integration-tests.yml#L16)
LOW|Unpinned Actions Full Length Commit SHA|/run\-integration\-tests\.yml: [29](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/run-integration-tests.yml#L29)
LOW|Unpinned Actions Full Length Commit SHA|/ci\.yml: [28](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/ci.yml#L28)
LOW|Unpinned Actions Full Length Commit SHA|/cla\.yml: [23](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/cla.yml#L23)
LOW|Unpinned Actions Full Length Commit SHA|/release\-weekly\-docker\.yml: [24](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-weekly-docker.yml#L24)
LOW|Unpinned Actions Full Length Commit SHA|/release\-live\-docker\.yml: [41](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-live-docker.yml#L41)
LOW|Unpinned Actions Full Length Commit SHA|/release\-main\-docker\.yml: [30](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-main-docker.yml#L30)
LOW|Unpinned Actions Full Length Commit SHA|/release\-main\-docker\.yml: [33](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-main-docker.yml#L33)
LOW|Unpinned Actions Full Length Commit SHA|/release\-main\-docker\.yml: [46](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-main-docker.yml#L46)
LOW|Unpinned Actions Full Length Commit SHA|/run\-integration\-tests\.yml: [22](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/run-integration-tests.yml#L22)
LOW|Unpinned Actions Full Length Commit SHA|/release\-main\-docker\.yml: [39](https://github.com/kingthorin/zaproxy/blob/pin-actions-sha//.github/workflows/release-main-docker.yml#L39)

**Comment by thc202** [comment]
Should wait for #8693.

**Comment by kingthorin** [comment]
Rebased current

**Comment by thc202** [comment]
The `snapcore/action-*` were not updated.

**Comment by kingthorin** [comment]
On it

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
