### PR TITLE
Request Plugin Id  for Feature Policy Scanner.

### PR DESCRIPTION
**Pull request by Ketharan**
Request for the plugin id (10063) for the new `pscanalpharule Feature Policy Scanner`

### CODE REVIEW

**Comment by thc202** [comment]
@Ketharan the commit email is not the expected, more details in:
https://help.github.com/en/articles/about-commit-email-addresses

**Comment by kingthorin** [comment]
Doing "close/reopen" in an attempt to get LGTM sorted.

**Comment by kingthorin** [comment]
LGTM/Github still seem to be having issues here for some reason. Might have to merge manually to temp disable LGTM.

image

**Comment by thc202** [comment]
@Ketharan do you plan to change the email of the commit? (Just making sure, other than that this looks good.)

**Comment by Ketharan** [comment]
Sorry. I changed the mail at the git (for future commits), instead of this.

**Comment by thc202** [comment]
Could you squash the commits? (Not sure the squash and merge would preserve the commit/email we want.)

**Comment by kingthorin** [comment]
Here are some details for doing an interactive rebase in order to fix-up or squash into a single commit.

- https://www.instructables.com/id/How-to-Rebase-Interactive-With-Eclipse-eGit/
- https://www.kernel.org/pub/software/scm/git/docs/git-rebase.html#_interactive_mode
- https://wiki.eclipse.org/EGit/User_Guide#Interactive_Rebase

**Comment by thc202** [comment]
This has more changes than needed, could you tweak that?

**Comment by kingthorin** [comment]
Let me know if you need help sorting it out. I don’t mind tackling it then describing how.

**Comment by Ketharan** [comment]
Is that fine now?

**Comment by kingthorin** [comment]
It’s three commits again. I’ll tackle it.

**Comment by kingthorin** [comment]
Fixed.

I thought about pulling it, doing a fixup, and rebasing it, and fixing the conflict. 

But given that it's a single line change and the impacted file has been changed between. It was easier to switch to a fresh (up-to-date) develop, re-implement the change, and then force push it to your repo.

BTW in the future you should use feature branches not work off the main branch (develop in this case).
https://nvie.com/posts/a-successful-git-branching-model/

**Comment by Ketharan** [comment]
Thanks. Got it. Sorry for the mess created.

**Comment by kingthorin** [comment]
> Thanks. Got it. Sorry for the mess created.

Don't worry at all. It happens to everyone.

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
