### PR TITLE
Remove ice4j dependency

### PR DESCRIPTION
**Pull request by thc202**
Remove usage of ice4j classes in deprecated/unused class and remove the dependency, no longer needed in core.

### CODE REVIEW

**Comment by kingthorin** [comment]
Has this been tested behind NAT?

**Comment by thc202** [comment]
This class is no longer used. The Network add-on does have the [required functionality](https://github.com/zaproxy/zap-extensions/blob/d8f533f9fd71c16128d5c08c64886433e7f7af06/addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/RecursiveRequestHandler.java#L201-L227).

**Comment by kingthorin** [comment]
Perfect.

**Review by kingthorin — APPROVED** [review]

**Review by ricekot — APPROVED** [review]
Thanks!

**Pull request merged**
