### PR TITLE
Deprecate and disable script API

### PR DESCRIPTION
**Pull request by thc202**
The API will be provided by the add-on.

Part of zaproxy/zaproxy#8027.

---
WIP until zaproxy/zap-extensions#5459 is merged.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Should all the endpoint be presented as deprecated?

**Comment by thc202** [comment]
They are still going to be provided by the add-on so not deprecated (only the core class is).

**Comment by kingthorin** [comment]
Okay

**Comment by thc202** [comment]
Removed WIP.

**Review by psiinon — APPROVED** [review]

**Pull request merged**
