### PR TITLE
Tweak log message in URLCanonicalizer

### PR DESCRIPTION
**Pull request by thc202**
Change a log message to include the URL that is being processed, also
change to return immediately if the the URL is not valid after logging
the problem (instead of throwing an exception, which would be caught
(and logged) in the same method).

### CODE REVIEW

**Comment by psiinon** [comment]
Are warnings the most useful thing at this level? (I know its the current behaviour;)
Might it be better to throw exceptions and then allow the caller to decide if it wants to warn / ignore etc?

**Comment by thc202** [comment]
I think warning is useful, the spider should be able to resolve all URLs correctly and it's good to know when they are not (e.g. in the case it's an issue in the extraction of the URLs #2898). Maybe it should (also) be shown to the user? Spider tab?
At the moment the class is only used by spider related classes, so the behaviour of the callers would end up being the same ("warn and return"). If we plan to use it in other places we should probably extract it to other package and remove some of the spider related logic (e.g. strip of session parameters and other "cleaning" methods).

**Comment by psiinon** [comment]
I agree - I think this info is useful to the user, in which case I think it should be shown in the UI rather than reported in the logs. And the spider tab sounds like the right place for it to me - we could always make this an option.

**Comment by thc202** [comment]
OK, should those changes be done for 2.6.0?

**Comment by psiinon** [comment]
Would be nice, but def not a blocker (imo)

**Comment by thc202** [comment]
OK, thanks.

**Pull request merged**
