### PR TITLE
CSP Scanner Plugin ID Reservation

### PR DESCRIPTION
**Pull request by kingthorin**
Reserve plugin ID 10055 for CSP passive scanner. See zaproxy/zaproxy#527

### CODE REVIEW

**Comment by thc202** [comment]
Any reason to not use 10038 (i.e. change the existing scanner to do the new checks)?

**Comment by kingthorin** [comment]
Mainly that's it'd require an aver haul because it's no longer just "missing". It can be done though if that's the preference.

**Comment by kingthorin** [comment]
If the team agrees that overhaul is a better idea then I'm good with that. This PR can just be closed.

**Comment by thc202** [comment]
It does not require many changes, just a rename of the class and a change of the messages prefix. (It would not be the first to be changed to do more checks, XFO scanner was initially just checking if the header was missing.)
IMHO it would be better to have the related CSP checks in the same scanner (the current one already has a TODO to do more checks), but I'm OK with both ways.

**Comment by kingthorin** [comment]
Ok, I can agree with that. Closing this in favour of using 10038.

**Comment by kingthorin** [comment]
IRC update: Reopening. Will create a separate pscan addon and use 10055 for the new rule.

See zaproxy/zaproxy#527 for further details.

**Comment by thc202** [comment]
Looks good to me.

**Pull request merged**
