### PR TITLE
Redirect core API reports to report add-on

### PR DESCRIPTION
**Pull request by psiinon**
Depends on https://github.com/zaproxy/zap-extensions/pull/2999 - will not work properly until thats merged.

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Ugh, will whitelist the JApicmp issues...

**Comment by psiinon** [comment]
Also need to reinstate some of the classes used by existing add-ons...

**Comment by thc202** [comment]
The resource messages no longer used should be removed.

**Comment by psiinon** [comment]
FYI I'll change this PR so that we keep the reporting classes for now - that will mean the weekly will still work with add-ons that depend on them (like CodeDX).

**Comment by psiinon** [comment]
No longer deleting the core classes so old add-ons that use then should keep working.
Ready for review.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
