### PR TITLE
Update Gradle to 7.0

### LINKED ISSUE #6511: Unable to run ZAP from source with Java 16
**Describe the bug**
Error at building the project from source code.  Based on the documentation located in the following URL https://www.zaproxy.org/docs/developer/quick-start-build/ 

**To Reproduce**
1. Navigate to the cloned zaproxy folder and run the following command ./gradlew run 
2. See error  "**java.lang.NoClassDefFoundError: could not initialize class org.codehaus.groovy.runtime.invokerhelper "**'

**Expected behavior**
“Dev Build” loading window.

**Software versions**
 - ZAP: latest repo version v2.10.0
 - Add-on: 
 - OS: MacOS Big Sur 11.2.3 (20D91)
 - Java: openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+36-2231)
OpenJDK 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)
- gradle 6.8.3
**Errors from the zap.log file**

**Additional context**

**Would you like to help fix this issue?**
I'd like to try and help fix this issue.
I modified the following file "gradle-wrapper.properties" under zaproxy/gradle/wrapper and changed the value "distributionUrl" to https://services.gradle.org/distributions/gradle-6.6.1-bin.zip and the error disappear

### PR DESCRIPTION
**Pull request by thc202**
Update Gradle Wrapper and build to 7.0.
Update Spotless to 5.12.1.
Update Linux Packaging plugin to 8.5.6.
Update Download Task plugin to 4.1.1.
Update install4j plugin:
 - Use 9.0.2 if Java >= 11, required by the new version;
 - Use older version if Java < 11, to just compile;
 - Disable installers task if Java < 11, no longed functional;
 - Set up toolchain to build ZAP with Java 8 when releasing and update
 release workflows to use Java 11.

Update Launch4j plugin to 2.5.0.
Update JaCoCo to 0.5.6.

Fix #6511.

---
There are still some deprecation warnings caused by a plugin (we'll have to wait for a new version).

### CODE REVIEW

**Comment by thc202** [comment]
One of the plugins require newer Java version, need to check if there's an older one compatible with Java 8.

**Comment by thc202** [comment]
No, the latest version that works with Java 8 is not compatible with Gradle 7, i.e.:
```
* What went wrong:
A problem was found with the configuration of task ':zap:installers' (type 'Install4jTask').
  - Type 'Install4jTask' property 'variablesTempFile$gradle_plugin' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
```

will check if it's possible to workaround that...

**Comment by thc202** [comment]
I'm not seeing a way of addressing that, since this is just for the installers we can make that optional (i.e. use Java 11 for the build but still compile ZAP with Java 8, when doing the release).

**Comment by thc202** [comment]
Done.

**Review by psiinon — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]
Thanks!

**Pull request merged**
