### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by rhowe**
A bunch of somewhat scattered cleanups.

I think these are all still Java8 compatible (at least that's what IntelliJ thinks).

Clear out unused code in `ZapNumberSpinner` and do some misc. tidyups there.
Remove the unused Undo Manager stuff from text components
Replace some `for` loops with `foreach` loops or Streams
Remove the long-unused `HtmlContextAnalyser` class

### CODE REVIEW

**Comment by thc202** [comment]
The code removed is actually in use (or might be) by add-ons.

**Comment by rhowe** [comment]
> The code removed is actually in use (or might be) by add-ons.

Ah, I did wonder how exposed it would be. Does this extend to the Undo Manager stuff as well?

**Comment by rhowe** [comment]
Closing in favour of https://github.com/zaproxy/zaproxy/pull/5554

**Comment by thc202** [comment]
> Does this extend to the Undo Manager stuff as well?

Yes, it applies to those changes too (in any case it would have to be deprecated first).

**Pull request closed without merging**
