### PR TITLE
Fixes #1967: View current session location via API

### LINKED ISSUE #1967: Query Session Location via API
Missing: http://localhost:8080/UI/core/view/sessionLocation/
to display the full path of of the current session.

The value is already used in the GUI:
https://github.com/zaproxy/zaproxy/blob/2.4/src/org/parosproxy/paros/view/SessionGeneralPanel.java#L139

Needed for moving the session into a FTP directory after automated scan.

### PR DESCRIPTION
**Pull request by yannicsmeets**
Allows users to retrieve the location of the current session file via the API

### CODE REVIEW

**Comment by psiinon** [comment]
This is actually a tricky one. One of the reasons we havnt supported this to date is because it leaks information - a remote site can use this to gain information about the pentesters computer.
I'm not sure we should support it without extra safeguards, eg such as requiring the API key.
This might be one to discuss on the dev group - I'll start a thread there in a bit..

**Comment by Harinus** [comment]
There also exists the function: core/view/homeDirectory which exposes path information without the API key. Maybe you should consider reviewing this one as it is pretty similar to my requested feature in #1967. I don't know if it is intended behaviour but the homeDirectory is set when opening any saved session but not when opening a new session. Otherwise I could use this one for my needs. Requiring the API key would be fine for me though.

**Comment by yannicsmeets** [comment]
Has anything been decided on this already?

**Comment by Harinus** [comment]
Is there still no decision on these 5 lines of code?

**Comment by kingthorin** [comment]
@yannicsmeets as Simon suggested please ensure this requires apikey

**Comment by kingthorin** [comment]
@yannicsmeets is an update coming?

**Comment by yannicsmeets** [comment]
I'm sorry no, I currently don't have any time

**Comment by kingthorin** [comment]
Could you set this PR to allow modification by maintainers?
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by yannicsmeets** [comment]
I can't see the checkbox to allow edits. Probably because the source branch is missing (i don't know why that happened, seems to be deleted). Is there another way to do this?

**Comment by thc202** [comment]
That happens when the fork is deleted, not sure if that can be fixed. The only options, I think, is to either manually merge the pull request or open a new one.

**Pull request merged**
