### PR TITLE
Update links to Github instead of code.google

### PR DESCRIPTION
**Pull request by Paulmolin**
I replaced every link to code.google.com I could find with the new Github links (or Sourceforge if appropriate). Are you interested?

### CODE REVIEW

**Comment by psiinon** [comment]
Definitely interested :D
Couple of minor points:
I think it would be better for the downloads link to be https://github.com/zaproxy/zaproxy/wiki/Downloads - that links to sourceforge, and hopefully this is less likely to change.
Only the Messages.properties file needs to be changed - the Messages_*.properties files are imported from Crowdin, and any changes to those will be lost if those ones arent changed.
The Contant.properties file has some indentation changes which arent necessary and can confuse things.
Many thanks

**Comment by Paulmolin** [comment]
I changed zaproxy:master

**Comment by Paulmolin** [comment]
I made the changes you asked for! :)

**Comment by thc202** [comment]
Could you update the commit message too? (i.e. drop reference to SourceForge)

Thank you.

**Comment by Paulmolin** [comment]
Yup, it's done!

**Comment by psiinon** [comment]
Many thanks!

**Comment by Paulmolin** [comment]
You're welcome! :)

**Pull request merged**
