### PR TITLE
Updated installers for 2.7.0

### PR DESCRIPTION
**Pull request by psiinon**

### CODE REVIEW

**Comment by thc202** [comment]
Worth updating `macOsJreDirName` for the new Java version?

**Comment by psiinon** [comment]
Good spot! Now done.

**Comment by psiinon** [comment]
Doh! Fixed :)

**Comment by psiinon** [comment]
And just fixed a bug - the wrong mac os dir was being used

**Comment by psiinon** [comment]
Reverted the mac dir change - that was right, I must have just done something wrong ;)

**Pull request merged**
