### PR TITLE
Tooltip Title Caps

### PR DESCRIPTION
**Pull request by aayushhyadav**
Related to - #2000 
Signed-off-by: Aayush <aayushmum@gmail.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Based on a quick skim these seem okay. I still need to pull the branch and look at where they're actually used.

**Comment by kingthorin** [comment]
Sorry for the delay, I'll try to tackle this over the weekend.

**Comment by thc202** [comment]
Ping @kingthorin :)

**Comment by kingthorin** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Pulled and reviewed, LGTM.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

We'll have to update the help I think.

**Pull request merged**
