### PR TITLE
Warn when unable to save malformed HTTP message

### LINKED ISSUE #4235: Warn when unable to save (malformed) HTTP message in Request/Response panels
Issue reported in OWASP ZAP User Group: https://groups.google.com/d/topic/zaproxy-users/O18H5nV7sf0/discussion

Steps to reproduce the issue:
1. Run ZAP;
2. Send a well-formed request through the Manual Request Editor dialogue:
```
GET http://example.org/ HTTP/1.1
Host: example.org
```
Note in the History tab that the GET request was sent;
3. Send a malformed request:
```
POSThttp://example.org/ HTTP/1.1
Host: example.org
```
and note that the actual request sent (History tab) was again a GET.
In the log there's a warning:
```
[AWT-EventQueue-0] WARN org.zaproxy.zap.extension.httppanel.view.impl.models.http.request.RequestHeaderStringHttpPanelViewModel  - Could not Save Header: POSThttp://example.org/ HTTP/1.1
Content-Length: 0
Host: example.org


org.parosproxy.paros.network.HttpMalformedHeaderException: Failed to find pattern: (\w+) +([^\r\n]+) +(HTTP/\d+\.\d+)
	at org.parosproxy.paros.network.HttpRequestHeader.parse(HttpRequestHeader.java:378)
	at org.parosproxy.paros.network.HttpRequestHeader.setMessage(HttpRequestHeader.java:214)
	at org.parosproxy.paros.network.HttpRequestHeader.setMessage(HttpRequestHeader.java:237)
	at org.parosproxy.paros.network.HttpRequestHeader.<init>(HttpRequestHeader.java:148)
	at org.parosproxy.paros.network.HttpMessage.setRequestHeader(HttpMessage.java:296)
	at org.zaproxy.zap.extension.httppanel.view.impl.models.http.request.RequestHeaderStringHttpPanelViewModel.setData(RequestHeaderStringHttpPanelViewModel.java:46)
	at org.zaproxy.zap.extension.httppanel.view.syntaxhighlight.HttpPanelSyntaxHighlightTextView.save(HttpPanelSyntaxHighlightTextView.java:185)
	at org.zaproxy.zap.extension.httppanel.component.HttpPanelComponentViewsManager.save(HttpPanelComponentViewsManager.java:299)
	at org.zaproxy.zap.extension.httppanel.component.split.request.RequestSplitComponent.save(RequestSplitComponent.java:180)
	at org.zaproxy.zap.extension.httppanel.HttpPanel.saveData(HttpPanel.java:333)
	at org.parosproxy.paros.extension.manualrequest.ManualRequestEditorDialog$2.actionPerformed(ManualRequestEditorDialog.java:177)
```

Remarks:
ZAP should warn (UI message) and fail to send the message instead of sending another (different) one.

ZAP
Version 2.7.0 (and older).

### PR DESCRIPTION
**Pull request by thc202**
Change models to throw an exception if unable to create the HTTP headers
instead of just logging a warning and continue, to allow to show the
error to the user.
Change Manual Request Editor and Break to warn if the data was not
actually set into the message.
Warn when unable to switch components, views, and HTTP method.

Fix #4235.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
Thanks

**Comment by kingthorin** [comment]
Open an issue to port this to requester? Or are you already tackling that?

**Comment by psiinon** [comment]
Looks good.
Are you going to address the new LGTM alert?

**Comment by thc202** [comment]
I don't plan to, that's a false positive (the code is exactly the same as before, `isCurrentComponent` is still checking that's non-null).

**Review by psiinon — APPROVED** [review]

**Pull request merged**
