### PR TITLE
chore: Upgrade Dependencies

### PR DESCRIPTION
**Pull request by kingthorin**
https://logging.apache.org/log4j/2.x/changes-report.html#a2.17.2

Log4j to 2.17.2
flatlaf to 2.0.2
rsyntxtextarea to 3.2.0

As well as junit/mockito bits, errorprone, and versions.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Comment by kingthorin** [comment]
Yes I do believe the jgrapht update was problematic.

I'll tackle the others.

**Comment by kingthorin** [comment]
Guess I'll revert the hsqldb change :wink:

**Comment by kingthorin** [comment]
Done

**Comment by kingthorin** [comment]
Done

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
