### PR TITLE
Add recommended security headers to the ZAP API UI

### LINKED ISSUE #2637: Prevent API UI from being loaded in a frame
Prevent the API UI from being loaded in a frame using a suitable X-Frame-Options header.
This wont work with some older browsers, but I dont think we need to support them - maybe we should recommend only using modern browsers with ZAP somewhere?
Reported via Bugcrowd - thanks to the relevant security researcher

### PR DESCRIPTION
**Pull request by psiinon**
Fixes #2637

### CODE REVIEW

**Comment by kingthorin** [comment]
Looks good

**Comment by psiinon** [comment]
Updated a couple of places that set headers directly and added a 'fixes' comment

**Comment by kingthorin** [comment]
Looks even better :)

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
