### PR TITLE
Push Docker images to GHCR

### PR DESCRIPTION
**Pull request by ricekot**

### CODE REVIEW

**Comment by kingthorin** [comment]
Are there any storage limits we need to worry about?

**Comment by ricekot** [comment]
According to https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages#about-billing-for-github-packages, there aren't any storage limits for public packages:

> GitHub Packages usage is free for public packages. For private packages, each account on GitHub.com receives a certain amount of free storage and data transfer

**Comment by kingthorin** [comment]
I think the changes look fine. My only other question is whether having different names in different repos/sources is going to cause us support headaches. (Though I'm probably over thinking that.)

**Comment by psiinon** [comment]
@kingthorin yeah, we chatted about that in IRC. Somehow the zap2docker names didnt seem to make sense in GHCR. TBH I'd like to change them in Docker too but thats probably not sensible 😉

**Review by psiinon — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
