### PR TITLE
Add PostgreSQL support

### PR DESCRIPTION
**Pull request by iMinusMinus**
add postgresql support

### CODE REVIEW

**Comment by psiinon** [comment]
@iMinusMinus thanks for adding this :) Have you tested it? If so, does ZAP work well with PostgreSQL? :)

**Comment by kingthorin** [comment]
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Comment by iMinusMinus** [comment]
> @iMinusMinus thanks for adding this :) Have you tested it? If so, does ZAP work well with PostgreSQL? :)

sorry,  i just test a few case. i find some bugs and updated

**Comment by psiinon** [comment]
The build failed :/
You'll need to run './gradlew :zap:spotlessApply' to fix these violations.
And see https://github.com/zaproxy/zaproxy/pull/7044/checks?check_run_id=5197516582 for fixing the failed DCO check.

**Comment by thc202** [comment]
@iMinusMinus ping.

**Comment by kingthorin** [comment]
If you rebase instead of merging this will be much cleaner.

**Pull request closed without merging**
