### PR TITLE
Add Jump To History functionality

### PR DESCRIPTION
**Pull request by kingthorin**
- ExtensionHistory > Hook the new popup menu item. Fix NPE in showInHistory method when History tab doesn't have focus.
- PopupMenuJumpTo > New functionality.
- Messages.properties > Supporting name/value pairs.

Part of zaproxy#7362

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
I'm really happy with how this came together in the end. Are there any tests I should be adding?

**Comment by kingthorin** [comment]
Deconflicted and ready for review.

**Comment by kingthorin** [comment]
I'll open a core-help PR after this is merged.

**Comment by kingthorin** [comment]
image

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Comment by kingthorin** [comment]
Whoop whoop 🎉🚀

**Comment by kingthorin** [comment]
I'll get the help PR put together tonight or tomorrow.

**Pull request merged**
