### PR TITLE
Update localized resources

### LINKED ISSUE #7055: Doubled apostrophes in (at least) the French translation
**Describe the bug**
All apostrophes are doubled in menus, labels and text blocks in Zaproxy when set to language `fr_FR`. This is not correct. I appears the Crowdin exports (translation files) are responsible for this.

**To Reproduce**
1. Go to Tools > Language
2. Set Language to `français`
3. Unfold the "Outils" (Tools) menu
4. First item in menu displays as `Naviguer dans l''API` (note the doubled apostrophe)
5. A few other obvious occurrences, under the "Vue" menu: `Activer l''image dans l''historique` and `Afficher l''onglet`

**Expected behavior**
Apostrophes should only appear once in every occurrence.

**Screenshots**
2022-01-29_14-10-36_capture
2022-01-29_14-11-18_capture
2022-01-29_14-11-25_capture
2022-01-29_14-11-41_capture

**Software versions**
```
OWASP ZAP
Version: 2.11.1
---
Installed Add-ons: [[id=alertFilters, version=13.0.0],
[id=ascanrules, version=44.0.0], [id=automation,
version=0.11.0], [id=bruteforce, version=11.0.0],
[id=callhome, version=0.3.0], [id=commonlib, version=1.6.0],
[id=coreLang, version=14.0.0], [id=diff, version=11.0.0],
[id=directorylistv1, version=5.0.0], [id=domxss,
version=12.0.0], [id=encoder, version=0.6.0], [id=exim,
version=0.0.1], [id=formhandler, version=4.0.0], [id=fuzz,
version=13.6.0], [id=gettingStarted, version=13.0.0],
[id=graaljs, version=0.2.0], [id=graphql, version=0.7.0],
[id=help, version=14.0.0], [id=hud, version=0.13.0],
[id=importurls, version=9.0.0], [id=invoke, version=11.0.0],
[id=jxbrowser, version=10.0.0], [id=jxbrowserlinux64,
version=8.0.0], [id=network, version=0.0.1], [id=oast,
version=0.8.0], [id=onlineMenu, version=9.0.0], [id=openapi,
version=25.0.0], [id=pscanrules, version=38.0.0],
[id=quickstart, version=33.0.0], [id=replacer,
version=9.0.0], [id=reports, version=0.10.0], [id=retest,
version=0.2.0], [id=retire, version=0.9.0], [id=reveal,
version=4.0.0], [id=saverawmessage, version=7.0.0],
[id=savexmlmessage, version=0.3.0], [id=scripts,
version=29.0.0], [id=selenium, version=15.6.0], [id=soap,
version=12.0.0], [id=spiderAjax, version=23.7.0], [id=tips,
version=9.0.0], [id=webdriverlinux, version=35.0.0],
[id=websocket, version=24.0.0], [id=zest, version=35.0.0]]
---
Operating System: Linux
Java Version: Oracle Corporation 11.0.13
System''s Locale: fr_FR
Display Locale: fr_FR
Format Locale: fr_FR
ZAP Home Directory: /home/karthanis/.ZAP/
ZAP Installation Directory: /usr/share/zaproxy/./
Look and Feel: FlatLaf Dark (com.formdev.flatlaf.FlatDarkLaf)
```

**Errors from the zap.log file**
N/A

**Additional context**
The doubled apostrophes can be found in the Crowdin exports, see for example: https://github.com/zaproxy/zaproxy/blob/d99c57fd3bfd084c9e8c82a97c071ae16c56f044/zap/src/main/dist/lang/Messages_fr_FR.properties#L76

I suppose the bug itself goes as far back as https://github.com/essiembre/eclipse-rbe/issues/8, but I think overall it's a Crowdin issue. They provide a guide as to how to treat apostrophes ("single quotes") here: https://support.crowdin.com/enterprise/configuration-file/?q=quote#escape-quotes-options-for-properties-file-format

**Would you like to help fix this issue?**
Not sure I can, it's a matter of messing with the Crowdin project configuration to escape apostrophes correctly, so maybe this is for the Crowdin project owner to do.

### PR DESCRIPTION
**Pull request by zapbot**
Update resources from Crowdin.

Fix #7055.

### CODE REVIEW

**Review by thc202 — APPROVED** [review]

**Review by ricekot — APPROVED** [review]

**Comment by thc202** [comment]
We should release a new language pack.

**Comment by karthanistyr** [comment]
@thc202 has this happened yet? If so, where would it be released? Marketplace lists a language pack dating back to Nov. 2021 

Capture_2022-02-13_12-44-00 257856469

**Comment by thc202** [comment]
It didn't happen.

**Comment by thc202** [comment]
The add-on is now available in the Marketplace.

**Pull request merged**
