### PR TITLE
Fix to run Docker images on Mac M1

### PR DESCRIPTION
**Pull request by darunesh-RH**
How to run zaproxy on Mac M1.

**darunesh@darunesh-mac docker % uname -a**
Darwin darunesh-mac 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64
**darunesh@darunesh-mac docker %** 
**darunesh@darunesh-mac docker % docker build -t zapm1 -f Dockerfile-stable .**
[+] Building 1.3s (31/31) FINISHED                                                                                                                                                                                    
 => [internal] load build definition from Dockerfile-stable                                                                                                                                                      
 => => naming to docker.io/library/zapm1                                                                                                                                                                         0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

darunesh@darunesh-mac docker % docker images  
REPOSITORY           TAG               IMAGE ID       CREATED              SIZE
zapm1                latest            15511dbd1fb5   About a minute ago   1.82GB

**darunesh@darunesh-mac docker % docker run -it zapm1:latest**
**zap@180f8295b903:/zap$ ls**
CHANGELOG.md  container  lang  license  scripts   xml             zap-api-scan.py  zap-full-scan.py  zap-x.sh  zap.ico  zap_common.py
README        db         lib   plugin   webswing  zap-2.11.1.jar  zap-baseline.py  zap-webswing.sh   zap.bat   zap.sh
**zap@180f8295b903:/zap$ ./zap.sh -cmd -quickurl https://example.com -quickprogress -quickout ~/result.xml**
Found Java version 11.0.15
Available memory: 7851 MB
Using JVM args: -Xmx1962m
517 [main] INFO  org.parosproxy.paros.Constant - Copying default configuration to /home/zap/.ZAP/config.xml
624 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP/session
624 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP/dirbuster
624 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP/fuzzers
625 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP/plugin
May 09, 2022 3:49:46 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Accessing URL
Using traditional spider
Active scanning
[====================] 100% 
Attack complete
Writing results to /home/zap/result.xml
zap@180f8295b903:/zap$

### CODE REVIEW

**Comment by psiinon** [comment]
Switching the image we build on top of is a very significant change and not something I think we should do lightly.
I'm not saying I'm against this PR, but its not something I think we should merge without careful consideration of the implications.

**Comment by feuillemorte** [comment]
Hi!

@psiinon, sorry for dumb questions, but could you clarify me one thing, please?

I can see that the existing image is already [multiplatform](https://hub.docker.com/layers/openjdk/library/openjdk/8-jdk-alpine/images/sha256-a3562aa0b991a80cfe8172847c8be6dbf6e46340b759c2b782f8b8be45342717?context=explore) (see the `OS/ARCH` list).

If I understand correctly then it's possible to build an image for [different platforms](https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/) even if your host platform is different from the target platform you build.

Not sure that it's needed, but the `platform` parameter also can be included in docker-compose file like this:

```
version: '3'
services:
  zap:
    # The base image is multiplatform.
    # Available options are:
    # linux/386
    # linux/amd64
    # linux/arm/v6
    # linux/arm/v7
    # linux/arm64/v8
    # linux/ppc64le
    # linux/s390x
    # linux/amd64
    # To build the image for Mac M1 please use the linux/arm64/v8 platform
    platform: ${PLATFORM}
    build: 
      context: .
      dockerfile: ${DOCKERFILE_NAME}
    ports:
      - 8090:8090
<......>
```

@psiinon, I don't know how your pipelines build the official images, so could you tell me, please, is it be possible to build an official multiplatform image somehow? I believe that @darunesh-RH could help you with testing.

We just built a custom image using the original docker file (without changes) and looks like it works fine. 

P.S. I would appreciate it someone else with M1 could try to build the custom image and check that it works fine to exclude some random factors:

```bash
git clone https://github.com/zaproxy/zaproxy.git
cd zaproxy/docker
docker build -t mycustomzap -f Dockerfile-stable --platform="linux/arm64/v8" .
```

**Comment by J12934** [comment]
Hi @feuillemorte 👋

Can confirm that it works fine on my m1 mac. 

`docker build -t local/zap -f docker/Dockerfile-stable ./docker` 
Works and the image build by it seems to be running normally.
So I don't think any changes to the dockerfile are needed for ARM support.

The build infrastructure zap uses should also be pretty easy to expand with multi-platform arm / x86 builds, as its already supported by the docker build and push action used.

 - ZAP Docker CI is this one here: https://github.com/zaproxy/zaproxy/blob/main/.github/workflows/release-weekly-docker.yml
- docker multi platform build and push docs: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md)

**Comment by thc202** [comment]
In the referenced issue they said "the webswing page hangs mid load.", could you check that Webswing works fine too?

**Comment by J12934** [comment]
@thc202 ah good point.

Webswing only works fine for me, but with the JAVA_HOME tweak described in the issue. (`docker run -u zap -p 8080:8080 -p 8090:8090 -e "JAVA_HOME=" -i local/zap zap-webswing.sh`)
Are we sure that this still needs to be hardcoded?

Screenshot 2022-05-14 at 23 00 23

**Comment by thc202** [comment]
That was present since the creation of the image (123c33e039cbbc25627e14cc6cf3e35ba51cd318), if ZAP and Webswing run fine without it I'm fine removing that, we can start doing that in live (just in case it breaks something).

@darunesh-RH would be good to know if you still have issues just removing the env var.

**Comment by darunesh-RH** [comment]
> That was present since the creation of the image ([123c33e](https://github.com/zaproxy/zaproxy/commit/123c33e039cbbc25627e14cc6cf3e35ba51cd318)), if ZAP and Webswing run fine without it I'm fine removing that, we can start doing that in live (just in case it breaks something).
> 
> @darunesh-RH would be good to know if you still have issues just removing the env var.

@thc202 I tried building Dockerfile-stable with and without JAVA_HOME path (https://github.com/zaproxy/zaproxy/blob/main/docker/Dockerfile-stable#L74), for me webswing works without JAVA_HOME in Dockerfile-stable on Mac M1.

darunesh@darunesh-mac docker % docker run -u zap -p 8080:8080 -p 8090:8090 -i myzapwithjavapath zap-webswing.sh 
Java installation not found in /usr/lib/jvm/java-11-openjdk-amd64/ folder
darunesh@darunesh-mac docker % docker run -u zap -p 8080:8080 -p 8090:8090 -i myzapwithoutjavapath zap-webswing.sh
Using ZAP command line options: -host 0.0.0.0 -port 8090

**Comment by thc202** [comment]
Closing, other changes (e.g. #7628) have been done to address the referenced issue.

**Pull request closed without merging**
