### PR TITLE
Support passive scan threading

### LINKED ISSUE #4394: Enhancement: Make Passive scanner thread safe
Further to:
https://github.com/zaproxy/zaproxy/issues/2528
https://github.com/zaproxy/zaproxy/pull/4318
and along with:
https://github.com/zaproxy/zaproxy/issues/4393

To facilitate further improvements and different usage models the passive scanner should be made thread safe.

### PR DESCRIPTION
**Pull request by psiinon**
Fixes #4394

OK, its a big change ;) 
I've submitted PRs for all of the add-ons which I know have threading problems but I'm sure more will come out of the woodwork soon enough :/

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Seems okay to me. Will try to pull it this evening and use it a bit.

**Comment by psiinon** [comment]
Updated to fix the LGTM JavaDoc issues.

**Comment by psiinon** [comment]
It looks like the option to pscan fuzzing requests is not getting updated, or its just always on.
And I've hit one ConcurrentModificationException which I'll need to fix...

**Comment by psiinon** [comment]
Think I've fixed the ConcurrentModificationException (in ExtensionParams.persist(..) - changed that to be synchronized)

**Comment by psiinon** [comment]
And fixed the switch on pscanning fuzzer messages - c-n-p bug ;)

**Comment by psiinon** [comment]
Pushed another concurrency fix, think thats done now...

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
