### PR TITLE
Add FUNDING.yml for GH Sponsor button

### PR DESCRIPTION
**Pull request by kingthorin**
Per: https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository

Using donate link from: https://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Does it work from the owasp page?

**Comment by psiinon** [comment]
Looks like the HTML on the current page is:
```
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
<input type="hidden" name="cmd" value="_donations">
<input type="hidden" name="business" value="owasp.foundation@owasp.org">
<input type="hidden" name="item_name" value="Zed Attack Proxy">
<input type="hidden" name="currency_code" value="USD">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" border="0">
<img alt="" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" border="0">
</form>
```

**Comment by kingthorin** [comment]
I'll see what I can do with it shortly.

**Comment by kingthorin** [comment]
Should be fixed.

**Comment by kingthorin** [comment]
Per IRC, closing in favor of default .github repo.

**Pull request closed without merging**
