### PR TITLE
Add option to show request/response in same tab

### LINKED ISSUE #4331: Allow to show Request and Response in the same tab
Hi, 

I think would be great if requester and request tab could share the same response tab. For laptops with a small screen, I have to change from normal layout to full layout when I'm working with the requester.

Best regards,

RLobo

### PR DESCRIPTION
**Pull request by thc202**
Add an option to toolbar (and entry in Options > Display), to show the
Request and Response panels in the same tab.

Fix #4331 - Allow to show Request and Response in the same tab

Tasks:
 - [x] Enable in Full Layout.
 - [x] Move icon position, to be consistent with other tabs.

### CODE REVIEW

**Comment by thc202** [comment]
Still WIP (e.g. shortcut to select or focus the request tab are not working properly) but good enough for feedback about the L&F.

**Comment by juhakivekas** [comment]
This looks great. I like that doubleclicking to fullscreen works even if full layout isn't supported. Tiny detail: all other tabs (except request) have the icon on the left side of the tab name, looks little inconsistent to my eye.

**Comment by thc202** [comment]
Right, we could enable this (along with "Tabs Side by Side") for full layout, the current ones were disable because they didn't make sense in full layout. Agreed, the icon in that position does not look good.

**Comment by thc202** [comment]
And thanks for feedback :)

**Comment by thc202** [comment]
Conflict resolved. It's now ready for review.

**Comment by juhakivekas** [comment]
Sweet :candy:

**Comment by sbzo** [comment]
Thanks, guys!!!! I will wait for the weekly release.

**Pull request merged**
