### PR TITLE
String Tweaks

### PR DESCRIPTION
**Pull request by MostafaMohamed888**
General - Fix Title Caps #2000
Screenshot from 2021-03-18 18-39-13

### CODE REVIEW

**Comment by kingthorin** [comment]
The two for time out looked good, the CFU one was unnecessary.

https://capitalizemytitle.com/style/Chicago/

**Comment by MostafaMohamed888** [comment]
i changed it back can you please take a look now :) @kingthorin

**Review by kingthorin — APPROVED** [review]
Thanks

**Comment by MostafaMohamed888** [comment]
can you please ping the second reviewer to review the PR? @kingthorin

**Review by psiinon — APPROVED** [review]

**Comment by thc202** [comment]
Might as well change other places to have the same form?

**Comment by kingthorin** [comment]
Consistency is a good move. It could be added to issue 2000.

**Pull request merged**
