### PR TITLE
WIP Initial Commit for issues/5278 with skeleton code

### PR DESCRIPTION
**Pull request by preetkaran20**

### CODE REVIEW

**Comment by kingthorin** [comment]
?

**Comment by thc202** [comment]
Seems the main branch was synced (and since there are no changes the PR was automatically closed).

**Comment by preetkaran20** [comment]
yes, actually i wanted to fresh start on this issue as per review comments and i was not aware that syncing main branch can close PR.

**Comment by kingthorin** [comment]
Well it would only close if the branches became equal (which means there's no longer a contribution).

**Pull request closed without merging**
