### PR TITLE
Reserving unique ID for CORS active scan rule

### PR DESCRIPTION
**Pull request by CravateRouge**
For more details, see: https://github.com/zaproxy/zap-extensions/pull/2705

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Review by kingthorin — DISMISSED** [review]

**Comment by kingthorin** [comment]
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Comment by thc202** [comment]
Changed to main branch, it has a conflict.

**Comment by kingthorin** [comment]
Good catch @thc202.

@CravateRouge I guess you'll need to use 40040.

**Comment by kingthorin** [comment]
Still conflicting.

**Comment by kingthorin** [comment]
Thanks

**Pull request merged**
