### PR TITLE
Docker: add zap_tune function and zap_tuned hook

### PR DESCRIPTION
**Pull request by psiinon**
Will ask on the dev group for any other suggestions..

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Seems the tests are having an issue.

**Comment by psiinon** [comment]
Yeah, but they also seem to be failing on develop for me as well :( Looking into it...

**Comment by psiinon** [comment]
Updated to also set max pscan alerts to 10 and to disable log recovery + added simple tests
Initial test fix c/o @thc202 :)

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
