### PR TITLE
Master

### PR DESCRIPTION
**Pull request by varshav21**
Made changes accordingly as suggested in #4349

### CODE REVIEW

**Comment by kingthorin** [comment]
If uou push to tue same origin branch as #4349 then there's no need for seperare PRs. 

Looking atvtge other that means develop not master.

**Comment by thc202** [comment]
Closing this for now, the changes can still be done in the other PR.

**Comment by varshav21** [comment]
Is it right if I create a pull request from varshav21:master branch to the zaproxy:develop again? Will the changes be added to the pr #4349 ?

**Comment by thc202** [comment]
No, you need to use your `develop` branch (that's the branch used to open that pull request). If you commit to that branch and push it will show up in that pull request.

**Pull request closed without merging**
