### PR TITLE
Remove PacScript

### PR DESCRIPTION
**Pull request by thc202**
Remove `PacScript` and related resources/dependencies, it will be moved
to Graal JS add-on (per Nashorn deprecation and removal in newer Java
versions).

Related to #265 and #4851.

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Comment by thc202** [comment]
Change breaks in Java 8.

**Comment by thc202** [comment]
Difference in how Nashorn converts the values in Java 8 and 11, the latter uses integer for integer values while the former uses float values.

This was to reduce the changes done to `PacScript` when moving to GraalJS add-on (which works the same in Java 8 and 11), will just remove it and do the required changes while moving...

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
Changed to remove the class and related files. WIP until it's in the add-on.

**Comment by thc202** [comment]
Removed WIP.

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
