### PR TITLE
License Cleanup

### PR DESCRIPTION
**Pull request by Jeymz**
Update to the license to remove template information.

### CODE REVIEW

**Comment by kingthorin** [comment]
What's this supposed to accomplish?

**Comment by Jeymz** [comment]
It's just fixing something that was looked over. Cleaning up the license to remove template info and hopefully prompt somebody to add the copyright info and date to the license. Low hanging fruit.

**Comment by kingthorin** [comment]
The content is exactly the same with the exception of one line which is a placeholder, which is irrelevant. LICENSE is correct for the repo, all source files have relevant copyright and owner/assignee designation.

For my two cents anyway.

@psiinon @thc202 @ricekot ?

**Comment by thc202** [comment]
Agreed.

**Pull request closed without merging**
