### PR TITLE
Fixes #2836

### LINKED ISSUE #2836: ZAP hsqldb OutOfMemoryError when deleting records on cleanup
How to reproduce, create a new session and one context, run one scan on a large site/app. The session file should be roughly 10.5GB and there will be around 200,000 records in the `HISTORY` table.

When closing ZAP, it will run a delete to try to delete all records of a certain HISTTYPE at once, this will result in a 

`org.hsqldb.HsqlException: java.lang.OutOfMemoryError: Java heap space`

ZAP will fail to close, the session has a chance of getting corrupted but the regardless of a corrupted session, zap ends in an unclean state.

### PR DESCRIPTION
**Pull request by JordanGS**
Fixes #2836

You can increase ram but that will not solve the issue, too many records are being deleted at one time. Deleting in batches is the solution to keep zap doing a clean shutdown. I tested various methods of deletion including but not limited to:

1. `DELETE FROM HISTORY WHERE HISTTYPE IN (14) LIMIT 1000`

2. `DELETE FROM HISTORY WHERE HISTTYPE = 14 LIMIT 1000`

3. `DELETE FROM HISTORY WHERE HISTTYPE = 14 LIMIT 100`

Also tested with rownum instead of limit and the fastest is 1. using the IN clause. It takes roughly 20 minutes to properly close when it is deleting 167,000 records in batches of 1,000.

**Original Error #2836**
How to reproduce, create a new session and one context, run one scan on a large site/app. The session file should be roughly 10.5GB and there will be around 200,000 records in the HISTORY table.

When closing ZAP, it will run a delete to try to delete all records of a certain HISTTYPE at once, this will result in a

org.hsqldb.HsqlException: java.lang.OutOfMemoryError: Java heap space

ZAP will fail to close, the session has a chance of getting corrupted but the regardless of a corrupted session, zap ends in an unclean state.

### CODE REVIEW

**Comment by thc202** [comment]
Looks good to me. thanks!

**Comment by kingthorin** [comment]
All 3 of us missed ZAP comment :( I'll open a pull for that shortly.

**Comment by JordanGS** [comment]
@kingthorin what do you mean?

**Comment by kingthorin** [comment]
The modification was to a paros file so it should have a ZAP comment per the dev guidelines: https://github.com/zaproxy/zaproxy/wiki/DevGuidelines

**Comment by JordanGS** [comment]
@kingthorin ahh poop, i completely forgot about that. Is that a new pull request or can the merge be updated?

**Comment by kingthorin** [comment]
I forgot too, and went ahead with the merge, so I'll just fire in another quick PR to address it...

**Comment by JordanGS** [comment]
@kingthorin thanks a lot! :)

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/pull/2841

**Pull request merged**
