### PR TITLE
Allow to skip pending scanners

### LINKED ISSUE #3739: Allow to skip pending scanners
From #3454:

> When you are on the Scan Progress dialog of an active scan, it lists a row for each scan type to run (or that has run), but only has a Skip button for the current scan type being run. I'd like to see 2 simple enhancements:
> 
> 1) ...
> 2) There be a skip button for every test category that has not run yet so you can skip individual test categories that have not run yet. (In addition to still being able to skip the currently running test category).

(1. being handled in #3454.)

### PR DESCRIPTION
**Pull request by thc202**
Change Scan Progress dialogue to also allow to skip pending scanners.

Fix #3739 - Allow to skip pending scanners

### CODE REVIEW

**Comment by psiinon** [comment]
Looks good but now has conflicts

**Comment by thc202** [comment]
Conflict resolved.

**Comment by kingthorin** [comment]
Now conflicting

**Comment by thc202** [comment]
Done.

**Pull request merged**
