### PR TITLE
Move docker dir to a top level dir

### PR DESCRIPTION
**Pull request by thc202**
Move the docker dir from build dir to a top level directory, to leave
the build dir just for build (transient) files/data, while the build dir
is not removed with the current build tool it will with the new one.

Needs update:
 - [x] `hub.docker.com/r/owasp/zap2docker-live/`;
 - [ ] `zap-mgmt-scripts` (zapbot/zap-mgmt-scripts#14);
 - [x] `zaproxy` (wiki);
 - [ ] `zaproxy.blogspot.com`;
 - [ ] ?

Let me know if it's missing anything, plan to update them when merged (except for the first which should be done just before merging, ideally).

### CODE REVIEW

**Comment by kingthorin** [comment]
Is this safe to merge or does it need to wait for the checklist items?

**Comment by thc202** [comment]
Yeah, let me prepare the changes in the other places first.

**Comment by thc202** [comment]
It can be merged now, main updates done.

**Comment by thc202** [comment]
All tasks done. Let me know if you spot anything  that still needs to be updated.

**Pull request merged**
