### PR TITLE
Integration tests for Form/JSON auth

### PR DESCRIPTION
**Pull request by psiinon**
Depends on https://github.com/zaproxy/zap-extensions/pull/3447 and a subsequent live build.
I'll also see if I can create 1 or more tests vs an online test site...

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Added login test on demo.testfire.net :)

**Comment by psiinon** [comment]
For info, this test passes when I run it in the desktop but fails on the command line :/
Investigating...

**Comment by psiinon** [comment]
Had to tweak the stat is was checking - not sure why (will look into that) but working for me now in docker.
Ready for review.

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
